//
// Created by Dave on 2/4/2024.
//

#ifndef JSMOOCH_EMUS_NESM6502_OPCODES_H
#define JSMOOCH_EMUS_NESM6502_OPCODES_H

#include "m6502_misc.h"

// This file mostly generated by m6502_core_generator.js in JSMoo

extern M6502_ins_func nesM6502_decoded_opcodes[0x103];

#endif //JSMOOCH_EMUS_NESM6502_OPCODES_H
