//
// Created by Dave on 2/4/2024.
//

#ifndef JSMOOCH_EMUS_NESM6502_OPCODES_H
#define JSMOOCH_EMUS_NESM6502_OPCODES_H

#include "m6502_misc.h"

// This file mostly generated by m6502_core_generator.js in JSMoo

void M6502_ins_NONE(struct M6502_regs *regs, struct M6502_pins *pins);
void M6502_ins_00_BRK(struct M6502_regs *regs, struct M6502_pins *pins); // BRK
void M6502_ins_01_ORA(struct M6502_regs *regs, struct M6502_pins *pins); // ORA (d,x)
void M6502_ins_05_ORA(struct M6502_regs *regs, struct M6502_pins *pins); // ORA d
void M6502_ins_06_ASL(struct M6502_regs *regs, struct M6502_pins *pins); // ASL d
void M6502_ins_08_PHP(struct M6502_regs *regs, struct M6502_pins *pins); // PHP
void M6502_ins_09_ORA(struct M6502_regs *regs, struct M6502_pins *pins); // ORA #
void M6502_ins_0A_ASL(struct M6502_regs *regs, struct M6502_pins *pins); // ASL A
void M6502_ins_0D_ORA(struct M6502_regs *regs, struct M6502_pins *pins); // ORA a
void M6502_ins_0E_ASL(struct M6502_regs *regs, struct M6502_pins *pins); // ASL a
void M6502_ins_10_BPL(struct M6502_regs *regs, struct M6502_pins *pins); // BPL r
void M6502_ins_11_ORA(struct M6502_regs *regs, struct M6502_pins *pins); // ORA (d),y
void M6502_ins_15_ORA(struct M6502_regs *regs, struct M6502_pins *pins); // ORA d,x
void M6502_ins_16_ASL(struct M6502_regs *regs, struct M6502_pins *pins); // ASL d,x
void M6502_ins_18_CLC(struct M6502_regs *regs, struct M6502_pins *pins); // CLC i
void M6502_ins_19_ORA(struct M6502_regs *regs, struct M6502_pins *pins); // ORA a,y
void M6502_ins_1D_ORA(struct M6502_regs *regs, struct M6502_pins *pins); // ORA a,x
void M6502_ins_1E_ASL(struct M6502_regs *regs, struct M6502_pins *pins); // ASL a,x
void M6502_ins_20_JSR(struct M6502_regs *regs, struct M6502_pins *pins); // JSR a
void M6502_ins_21_AND(struct M6502_regs *regs, struct M6502_pins *pins); // AND (d,x)
void M6502_ins_24_BIT(struct M6502_regs *regs, struct M6502_pins *pins); // BIT d
void M6502_ins_25_AND(struct M6502_regs *regs, struct M6502_pins *pins); // AND d
void M6502_ins_26_ROL(struct M6502_regs *regs, struct M6502_pins *pins); // ROL d
void M6502_ins_28_PLP(struct M6502_regs *regs, struct M6502_pins *pins); // PLP
void M6502_ins_29_AND(struct M6502_regs *regs, struct M6502_pins *pins); // AND #
void M6502_ins_2A_ROL(struct M6502_regs *regs, struct M6502_pins *pins); // ROL A
void M6502_ins_2C_BIT(struct M6502_regs *regs, struct M6502_pins *pins); // BIT a
void M6502_ins_2D_AND(struct M6502_regs *regs, struct M6502_pins *pins); // AND a
void M6502_ins_2E_ROL(struct M6502_regs *regs, struct M6502_pins *pins); // ROL a
void M6502_ins_30_BMI(struct M6502_regs *regs, struct M6502_pins *pins); // BMI r
void M6502_ins_31_AND(struct M6502_regs *regs, struct M6502_pins *pins); // AND (d),x
void M6502_ins_35_AND(struct M6502_regs *regs, struct M6502_pins *pins); // AND d,x
void M6502_ins_36_ROL(struct M6502_regs *regs, struct M6502_pins *pins); // ROL d,x
void M6502_ins_38_SEC(struct M6502_regs *regs, struct M6502_pins *pins); // SEC
void M6502_ins_39_AND(struct M6502_regs *regs, struct M6502_pins *pins); // AND a,y
void M6502_ins_3D_AND(struct M6502_regs *regs, struct M6502_pins *pins); // AND a,x
void M6502_ins_3E_ROL(struct M6502_regs *regs, struct M6502_pins *pins); // ROL a,x
void M6502_ins_40_RTI(struct M6502_regs *regs, struct M6502_pins *pins); // RTI
void M6502_ins_41_EOR(struct M6502_regs *regs, struct M6502_pins *pins); // EOR (d,x)
void M6502_ins_45_EOR(struct M6502_regs *regs, struct M6502_pins *pins); // EOR d
void M6502_ins_46_LSR(struct M6502_regs *regs, struct M6502_pins *pins); // LSR d
void M6502_ins_48_PHA(struct M6502_regs *regs, struct M6502_pins *pins); // PHA
void M6502_ins_49_EOR(struct M6502_regs *regs, struct M6502_pins *pins); // EOR #
void M6502_ins_4A_LSR(struct M6502_regs *regs, struct M6502_pins *pins); // LSR A
void M6502_ins_4C_JMP(struct M6502_regs *regs, struct M6502_pins *pins); // JMP a
void M6502_ins_4D_EOR(struct M6502_regs *regs, struct M6502_pins *pins); // EOR a
void M6502_ins_4E_LSR(struct M6502_regs *regs, struct M6502_pins *pins); // LSR a
void M6502_ins_50_BVC(struct M6502_regs *regs, struct M6502_pins *pins); // BVC r
void M6502_ins_51_EOR(struct M6502_regs *regs, struct M6502_pins *pins); // EOR (d),y
void M6502_ins_55_EOR(struct M6502_regs *regs, struct M6502_pins *pins); // EOR d,x
void M6502_ins_56_LSR(struct M6502_regs *regs, struct M6502_pins *pins); // LSR d,x
void M6502_ins_58_CLI(struct M6502_regs *regs, struct M6502_pins *pins); // CLI
void M6502_ins_59_EOR(struct M6502_regs *regs, struct M6502_pins *pins); // EOR a,y
void M6502_ins_5D_EOR(struct M6502_regs *regs, struct M6502_pins *pins); // EOR a,x
void M6502_ins_5E_LSR(struct M6502_regs *regs, struct M6502_pins *pins); // LSR a,x
void M6502_ins_60_RTS(struct M6502_regs *regs, struct M6502_pins *pins); // RTS
void M6502_ins_61_ADC(struct M6502_regs *regs, struct M6502_pins *pins); // ADC (d,x)
void M6502_ins_65_ADC(struct M6502_regs *regs, struct M6502_pins *pins); // ADC d
void M6502_ins_66_ROR(struct M6502_regs *regs, struct M6502_pins *pins); // ROR d
void M6502_ins_68_PLA(struct M6502_regs *regs, struct M6502_pins *pins); // PLA
void M6502_ins_69_ADC(struct M6502_regs *regs, struct M6502_pins *pins); // ADC #
void M6502_ins_6A_ROR(struct M6502_regs *regs, struct M6502_pins *pins); // ROR A
void M6502_ins_6C_JMP(struct M6502_regs *regs, struct M6502_pins *pins); // JMP (d)
void M6502_ins_6D_ADC(struct M6502_regs *regs, struct M6502_pins *pins); // ADC a
void M6502_ins_6E_ROR(struct M6502_regs *regs, struct M6502_pins *pins); // ROR a
void M6502_ins_70_BVS(struct M6502_regs *regs, struct M6502_pins *pins); // BVS r
void M6502_ins_71_ADC(struct M6502_regs *regs, struct M6502_pins *pins); // ADC (d),y
void M6502_ins_75_ADC(struct M6502_regs *regs, struct M6502_pins *pins); // ADC d,x
void M6502_ins_76_ROR(struct M6502_regs *regs, struct M6502_pins *pins); // ROR d,x
void M6502_ins_78_SEI(struct M6502_regs *regs, struct M6502_pins *pins); // SEI
void M6502_ins_79_ADC(struct M6502_regs *regs, struct M6502_pins *pins); // ADC a,y
void M6502_ins_7D_ADC(struct M6502_regs *regs, struct M6502_pins *pins); // ADC a,x
void M6502_ins_7E_ROR(struct M6502_regs *regs, struct M6502_pins *pins); // ROR a,x
void M6502_ins_81_STA(struct M6502_regs *regs, struct M6502_pins *pins); // STA (d,x)
void M6502_ins_84_STY(struct M6502_regs *regs, struct M6502_pins *pins); // STY d
void M6502_ins_85_STA(struct M6502_regs *regs, struct M6502_pins *pins); // STA d
void M6502_ins_86_STX(struct M6502_regs *regs, struct M6502_pins *pins); // STX d
void M6502_ins_88_DEY(struct M6502_regs *regs, struct M6502_pins *pins); // DEY
void M6502_ins_8A_TXA(struct M6502_regs *regs, struct M6502_pins *pins); // TXA
void M6502_ins_8C_STY(struct M6502_regs *regs, struct M6502_pins *pins); // STY a
void M6502_ins_8D_STA(struct M6502_regs *regs, struct M6502_pins *pins); // STA a
void M6502_ins_8E_STX(struct M6502_regs *regs, struct M6502_pins *pins); // STX a
void M6502_ins_90_BCC(struct M6502_regs *regs, struct M6502_pins *pins); // BCC
void M6502_ins_91_STA(struct M6502_regs *regs, struct M6502_pins *pins); // STA (d),y
void M6502_ins_94_STY(struct M6502_regs *regs, struct M6502_pins *pins); // STY d,x
void M6502_ins_95_STA(struct M6502_regs *regs, struct M6502_pins *pins); // STA d,x
void M6502_ins_96_STX(struct M6502_regs *regs, struct M6502_pins *pins); // STX d,y
void M6502_ins_98_TYA(struct M6502_regs *regs, struct M6502_pins *pins); // TYA
void M6502_ins_99_STA(struct M6502_regs *regs, struct M6502_pins *pins); // STA a,y
void M6502_ins_9A_TXS(struct M6502_regs *regs, struct M6502_pins *pins); // TXS
void M6502_ins_9D_STA(struct M6502_regs *regs, struct M6502_pins *pins); // STA a,x
void M6502_ins_A0_LDY(struct M6502_regs *regs, struct M6502_pins *pins); // LDY #
void M6502_ins_A1_LDA(struct M6502_regs *regs, struct M6502_pins *pins); // LDA (d,x)
void M6502_ins_A2_LDX(struct M6502_regs *regs, struct M6502_pins *pins); // LDX #
void M6502_ins_A4_LDY(struct M6502_regs *regs, struct M6502_pins *pins); // LDY d
void M6502_ins_A5_LDA(struct M6502_regs *regs, struct M6502_pins *pins); // LDA d
void M6502_ins_A6_LDX(struct M6502_regs *regs, struct M6502_pins *pins); // LDX d
void M6502_ins_A8_TAY(struct M6502_regs *regs, struct M6502_pins *pins); // TAY
void M6502_ins_A9_LDA(struct M6502_regs *regs, struct M6502_pins *pins); // LDA #
void M6502_ins_AA_TAX(struct M6502_regs *regs, struct M6502_pins *pins); // TAX
void M6502_ins_AC_LDY(struct M6502_regs *regs, struct M6502_pins *pins); // LDY a
void M6502_ins_AD_LDA(struct M6502_regs *regs, struct M6502_pins *pins); // LDA a
void M6502_ins_AE_LDX(struct M6502_regs *regs, struct M6502_pins *pins); // LDX a
void M6502_ins_B0_BCS(struct M6502_regs *regs, struct M6502_pins *pins); // BCS r
void M6502_ins_B1_LDA(struct M6502_regs *regs, struct M6502_pins *pins); // LDA (d),y
void M6502_ins_B4_LDY(struct M6502_regs *regs, struct M6502_pins *pins); // LDY d,x
void M6502_ins_B5_LDA(struct M6502_regs *regs, struct M6502_pins *pins); // LDA d,x
void M6502_ins_B6_LDX(struct M6502_regs *regs, struct M6502_pins *pins); // LDX d,y
void M6502_ins_B8_CLV(struct M6502_regs *regs, struct M6502_pins *pins); // CLV
void M6502_ins_B9_LDA(struct M6502_regs *regs, struct M6502_pins *pins); // LDA a,y
void M6502_ins_BA_TSX(struct M6502_regs *regs, struct M6502_pins *pins); // TSX
void M6502_ins_BC_LDY(struct M6502_regs *regs, struct M6502_pins *pins); // LDY a,x
void M6502_ins_BD_LDA(struct M6502_regs *regs, struct M6502_pins *pins); // LDA a,x
void M6502_ins_BE_LDX(struct M6502_regs *regs, struct M6502_pins *pins); // LDX a,y
void M6502_ins_C0_CPY(struct M6502_regs *regs, struct M6502_pins *pins); // CPY #
void M6502_ins_C1_CMP(struct M6502_regs *regs, struct M6502_pins *pins); // CMP (d,x)
void M6502_ins_C4_CPY(struct M6502_regs *regs, struct M6502_pins *pins); // CPY d
void M6502_ins_C5_CMP(struct M6502_regs *regs, struct M6502_pins *pins); // CMP d
void M6502_ins_C6_DEC(struct M6502_regs *regs, struct M6502_pins *pins); // DEC d
void M6502_ins_C8_INY(struct M6502_regs *regs, struct M6502_pins *pins); // INY
void M6502_ins_C9_CMP(struct M6502_regs *regs, struct M6502_pins *pins); // CMP #
void M6502_ins_CA_DEX(struct M6502_regs *regs, struct M6502_pins *pins); // DEX
void M6502_ins_CC_CPY(struct M6502_regs *regs, struct M6502_pins *pins); // CPY a
void M6502_ins_CD_CMP(struct M6502_regs *regs, struct M6502_pins *pins); // CMP a
void M6502_ins_CE_DEC(struct M6502_regs *regs, struct M6502_pins *pins); // DEC a
void M6502_ins_D0_BNE(struct M6502_regs *regs, struct M6502_pins *pins); // BNE r
void M6502_ins_D1_CMP(struct M6502_regs *regs, struct M6502_pins *pins); // CMP (d),y
void M6502_ins_D5_CMP(struct M6502_regs *regs, struct M6502_pins *pins); // CMP d,x
void M6502_ins_D6_DEC(struct M6502_regs *regs, struct M6502_pins *pins); // DEC d,x
void M6502_ins_D8_CLD(struct M6502_regs *regs, struct M6502_pins *pins); // CLD
void M6502_ins_D9_CMP(struct M6502_regs *regs, struct M6502_pins *pins); // CMP a,y
void M6502_ins_DD_CMP(struct M6502_regs *regs, struct M6502_pins *pins); // CMP a,x
void M6502_ins_DE_DEC(struct M6502_regs *regs, struct M6502_pins *pins); // DEC a,x
void M6502_ins_E0_CPX(struct M6502_regs *regs, struct M6502_pins *pins); // CPX #
void M6502_ins_E1_SBC(struct M6502_regs *regs, struct M6502_pins *pins); // SBC (d,x)
void M6502_ins_E4_CPX(struct M6502_regs *regs, struct M6502_pins *pins); // CPX d
void M6502_ins_E5_SBC(struct M6502_regs *regs, struct M6502_pins *pins); // SBC d
void M6502_ins_E6_INC(struct M6502_regs *regs, struct M6502_pins *pins); // INC d
void M6502_ins_E8_INX(struct M6502_regs *regs, struct M6502_pins *pins); // INX
void M6502_ins_E9_SBC(struct M6502_regs *regs, struct M6502_pins *pins); // SBC #
void M6502_ins_EA_NOP(struct M6502_regs *regs, struct M6502_pins *pins); // NOP
void M6502_ins_EC_CPX(struct M6502_regs *regs, struct M6502_pins *pins); // CPX a
void M6502_ins_ED_SBC(struct M6502_regs *regs, struct M6502_pins *pins); // SBC a
void M6502_ins_EE_INC(struct M6502_regs *regs, struct M6502_pins *pins); // INC a
void M6502_ins_F0_BEQ(struct M6502_regs *regs, struct M6502_pins *pins); // BEQ r
void M6502_ins_F1_SBC(struct M6502_regs *regs, struct M6502_pins *pins); // SBC (d),y
void M6502_ins_F5_SBC(struct M6502_regs *regs, struct M6502_pins *pins); // SBC d,x
void M6502_ins_F6_INC(struct M6502_regs *regs, struct M6502_pins *pins); // INC d,X
void M6502_ins_F8_SED(struct M6502_regs *regs, struct M6502_pins *pins); // SED
void M6502_ins_F9_SBC(struct M6502_regs *regs, struct M6502_pins *pins); // SBC a,y
void M6502_ins_FD_SBC(struct M6502_regs *regs, struct M6502_pins *pins); // SBC a,x
void M6502_ins_FE_INC(struct M6502_regs *regs, struct M6502_pins *pins); // INC a,x
void M6502_ins_100_S_RESET(struct M6502_regs *regs, struct M6502_pins *pins); // RESET
void M6502_ins_101_S_NMI(struct M6502_regs *regs, struct M6502_pins *pins); // NMI
void M6502_ins_102_S_IRQ(struct M6502_regs *regs, struct M6502_pins *pins); // IRQ

extern M6502_ins_func nesM6502_decoded_opcodes[0x103];

#endif //JSMOOCH_EMUS_NESM6502_OPCODES_H
