//
// Created by Dave on 2/4/2024.
//
#pragma once
#include "m6502_misc.h"

// This file mostly generated by m6502_core_generator.js in JSMoo
namespace M6502 {

extern ins_func nesdecoded_opcodes[0x103];

}