#pragma once
#include "sm83_misc.h"
namespace SM83 {
// This file generated by sm83_opcodes.js in JSMoo

void ins_00_NOP(regs &regs, pins &pins);
void ins_01_LD16_di_da(regs &regs, pins &pins); // BC
void ins_02_LD_ind_di(regs &regs, pins &pins); // BC, A
void ins_03_INC16_di(regs &regs, pins &pins); // BC
void ins_04_INC_di(regs &regs, pins &pins); // B
void ins_05_DEC_di(regs &regs, pins &pins); // B
void ins_06_LD_di_da(regs &regs, pins &pins); // B
void ins_07_RLCA(regs &regs, pins &pins);
void ins_08_LD16_addr_di(regs &regs, pins &pins); // SP
void ins_09_ADD16_di_di(regs &regs, pins &pins); // HL, BC
void ins_0A_LD_di_ind(regs &regs, pins &pins); // A, BC
void ins_0B_DEC16_di(regs &regs, pins &pins); // BC
void ins_0C_INC_di(regs &regs, pins &pins); // C
void ins_0D_DEC_di(regs &regs, pins &pins); // C
void ins_0E_LD_di_da(regs &regs, pins &pins); // C
void ins_0F_RRCA(regs &regs, pins &pins);
void ins_10_STOP(regs &regs, pins &pins);
void ins_11_LD16_di_da(regs &regs, pins &pins); // DE
void ins_12_LD_ind_di(regs &regs, pins &pins); // DE, A
void ins_13_INC16_di(regs &regs, pins &pins); // DE
void ins_14_INC_di(regs &regs, pins &pins); // D
void ins_15_DEC_di(regs &regs, pins &pins); // D
void ins_16_LD_di_da(regs &regs, pins &pins); // D
void ins_17_RLA(regs &regs, pins &pins);
void ins_18_JR_cond_rel(regs &regs, pins &pins); // 1
void ins_19_ADD16_di_di(regs &regs, pins &pins); // HL, DE
void ins_1A_LD_di_ind(regs &regs, pins &pins); // A, DE
void ins_1B_DEC16_di(regs &regs, pins &pins); // DE
void ins_1C_INC_di(regs &regs, pins &pins); // E
void ins_1D_DEC_di(regs &regs, pins &pins); // E
void ins_1E_LD_di_da(regs &regs, pins &pins); // E
void ins_1F_RRA(regs &regs, pins &pins);
void ins_20_JR_cond_rel(regs &regs, pins &pins); // regs.F.Z === 0
void ins_21_LD16_di_da(regs &regs, pins &pins); // HL
void ins_22_LD_ind_inc_di(regs &regs, pins &pins); // HL, A
void ins_23_INC16_di(regs &regs, pins &pins); // HL
void ins_24_INC_di(regs &regs, pins &pins); // H
void ins_25_DEC_di(regs &regs, pins &pins); // H
void ins_26_LD_di_da(regs &regs, pins &pins); // H
void ins_27_DAA(regs &regs, pins &pins);
void ins_28_JR_cond_rel(regs &regs, pins &pins); // regs.F.Z === 1
void ins_29_ADD16_di_di(regs &regs, pins &pins); // HL, HL
void ins_2A_LD_di_ind_inc(regs &regs, pins &pins); // A, HL
void ins_2B_DEC16_di(regs &regs, pins &pins); // HL
void ins_2C_INC_di(regs &regs, pins &pins); // L
void ins_2D_DEC_di(regs &regs, pins &pins); // L
void ins_2E_LD_di_da(regs &regs, pins &pins); // L
void ins_2F_CPL(regs &regs, pins &pins);
void ins_30_JR_cond_rel(regs &regs, pins &pins); // regs.F.C === 0
void ins_31_LD16_di_da(regs &regs, pins &pins); // SP
void ins_32_LD_ind_dec_di(regs &regs, pins &pins); // HL, A
void ins_33_INC16_di(regs &regs, pins &pins); // SP
void ins_34_INC_ind(regs &regs, pins &pins); // HL
void ins_35_DEC_ind(regs &regs, pins &pins); // HL
void ins_36_LD_ind_da(regs &regs, pins &pins); // HL
void ins_37_SCF(regs &regs, pins &pins);
void ins_38_JR_cond_rel(regs &regs, pins &pins); // regs.F.C === 1
void ins_39_ADD16_di_di(regs &regs, pins &pins); // HL, SP
void ins_3A_LD_di_ind_dec(regs &regs, pins &pins); // A, HL
void ins_3B_DEC16_di(regs &regs, pins &pins); // SP
void ins_3C_INC_di(regs &regs, pins &pins); // A
void ins_3D_DEC_di(regs &regs, pins &pins); // A
void ins_3E_LD_di_da(regs &regs, pins &pins); // A
void ins_3F_CCF(regs &regs, pins &pins);
void ins_40_LD_di_di(regs &regs, pins &pins); // B, B
void ins_41_LD_di_di(regs &regs, pins &pins); // B, C
void ins_42_LD_di_di(regs &regs, pins &pins); // B, D
void ins_43_LD_di_di(regs &regs, pins &pins); // B, E
void ins_44_LD_di_di(regs &regs, pins &pins); // B, H
void ins_45_LD_di_di(regs &regs, pins &pins); // B, L
void ins_46_LD_di_ind(regs &regs, pins &pins); // B, HL
void ins_47_LD_di_di(regs &regs, pins &pins); // B, A
void ins_48_LD_di_di(regs &regs, pins &pins); // C, B
void ins_49_LD_di_di(regs &regs, pins &pins); // C, C
void ins_4A_LD_di_di(regs &regs, pins &pins); // C, D
void ins_4B_LD_di_di(regs &regs, pins &pins); // C, E
void ins_4C_LD_di_di(regs &regs, pins &pins); // C, H
void ins_4D_LD_di_di(regs &regs, pins &pins); // C, L
void ins_4E_LD_di_ind(regs &regs, pins &pins); // C, HL
void ins_4F_LD_di_di(regs &regs, pins &pins); // C, A
void ins_50_LD_di_di(regs &regs, pins &pins); // D, B
void ins_51_LD_di_di(regs &regs, pins &pins); // D, C
void ins_52_LD_di_di(regs &regs, pins &pins); // D, D
void ins_53_LD_di_di(regs &regs, pins &pins); // D, E
void ins_54_LD_di_di(regs &regs, pins &pins); // D, H
void ins_55_LD_di_di(regs &regs, pins &pins); // D, L
void ins_56_LD_di_ind(regs &regs, pins &pins); // D, HL
void ins_57_LD_di_di(regs &regs, pins &pins); // D, A
void ins_58_LD_di_di(regs &regs, pins &pins); // E, B
void ins_59_LD_di_di(regs &regs, pins &pins); // E, C
void ins_5A_LD_di_di(regs &regs, pins &pins); // E, D
void ins_5B_LD_di_di(regs &regs, pins &pins); // E, E
void ins_5C_LD_di_di(regs &regs, pins &pins); // E, H
void ins_5D_LD_di_di(regs &regs, pins &pins); // E, L
void ins_5E_LD_di_ind(regs &regs, pins &pins); // E, HL
void ins_5F_LD_di_di(regs &regs, pins &pins); // E, A
void ins_60_LD_di_di(regs &regs, pins &pins); // H, B
void ins_61_LD_di_di(regs &regs, pins &pins); // H, C
void ins_62_LD_di_di(regs &regs, pins &pins); // H, D
void ins_63_LD_di_di(regs &regs, pins &pins); // H, E
void ins_64_LD_di_di(regs &regs, pins &pins); // H, H
void ins_65_LD_di_di(regs &regs, pins &pins); // H, L
void ins_66_LD_di_ind(regs &regs, pins &pins); // H, HL
void ins_67_LD_di_di(regs &regs, pins &pins); // H, A
void ins_68_LD_di_di(regs &regs, pins &pins); // L, B
void ins_69_LD_di_di(regs &regs, pins &pins); // L, C
void ins_6A_LD_di_di(regs &regs, pins &pins); // L, D
void ins_6B_LD_di_di(regs &regs, pins &pins); // L, E
void ins_6C_LD_di_di(regs &regs, pins &pins); // L, H
void ins_6D_LD_di_di(regs &regs, pins &pins); // L, L
void ins_6E_LD_di_ind(regs &regs, pins &pins); // L, HL
void ins_6F_LD_di_di(regs &regs, pins &pins); // L, A
void ins_70_LD_ind_di(regs &regs, pins &pins); // HL, B
void ins_71_LD_ind_di(regs &regs, pins &pins); // HL, C
void ins_72_LD_ind_di(regs &regs, pins &pins); // HL, D
void ins_73_LD_ind_di(regs &regs, pins &pins); // HL, E
void ins_74_LD_ind_di(regs &regs, pins &pins); // HL, H
void ins_75_LD_ind_di(regs &regs, pins &pins); // HL, L
void ins_76_HALT(regs &regs, pins &pins);
void ins_77_LD_ind_di(regs &regs, pins &pins); // HL, A
void ins_78_LD_di_di(regs &regs, pins &pins); // A, B
void ins_79_LD_di_di(regs &regs, pins &pins); // A, C
void ins_7A_LD_di_di(regs &regs, pins &pins); // A, D
void ins_7B_LD_di_di(regs &regs, pins &pins); // A, E
void ins_7C_LD_di_di(regs &regs, pins &pins); // A, H
void ins_7D_LD_di_di(regs &regs, pins &pins); // A, L
void ins_7E_LD_di_ind(regs &regs, pins &pins); // A, HL
void ins_7F_LD_di_di(regs &regs, pins &pins); // A, A
void ins_80_ADD_di_di(regs &regs, pins &pins); // A, B
void ins_81_ADD_di_di(regs &regs, pins &pins); // A, C
void ins_82_ADD_di_di(regs &regs, pins &pins); // A, D
void ins_83_ADD_di_di(regs &regs, pins &pins); // A, E
void ins_84_ADD_di_di(regs &regs, pins &pins); // A, H
void ins_85_ADD_di_di(regs &regs, pins &pins); // A, L
void ins_86_ADD_di_ind(regs &regs, pins &pins); // A, HL
void ins_87_ADD_di_di(regs &regs, pins &pins); // A, A
void ins_88_ADC_di_di(regs &regs, pins &pins); // A, B
void ins_89_ADC_di_di(regs &regs, pins &pins); // A, C
void ins_8A_ADC_di_di(regs &regs, pins &pins); // A, D
void ins_8B_ADC_di_di(regs &regs, pins &pins); // A, E
void ins_8C_ADC_di_di(regs &regs, pins &pins); // A, H
void ins_8D_ADC_di_di(regs &regs, pins &pins); // A, L
void ins_8E_ADC_di_ind(regs &regs, pins &pins); // A, HL
void ins_8F_ADC_di_di(regs &regs, pins &pins); // A, A
void ins_90_SUB_di_di(regs &regs, pins &pins); // A, B
void ins_91_SUB_di_di(regs &regs, pins &pins); // A, C
void ins_92_SUB_di_di(regs &regs, pins &pins); // A, D
void ins_93_SUB_di_di(regs &regs, pins &pins); // A, E
void ins_94_SUB_di_di(regs &regs, pins &pins); // A, H
void ins_95_SUB_di_di(regs &regs, pins &pins); // A, L
void ins_96_SUB_di_ind(regs &regs, pins &pins); // A, HL
void ins_97_SUB_di_di(regs &regs, pins &pins); // A, A
void ins_98_SBC_di_di(regs &regs, pins &pins); // A, B
void ins_99_SBC_di_di(regs &regs, pins &pins); // A, C
void ins_9A_SBC_di_di(regs &regs, pins &pins); // A, D
void ins_9B_SBC_di_di(regs &regs, pins &pins); // A, E
void ins_9C_SBC_di_di(regs &regs, pins &pins); // A, H
void ins_9D_SBC_di_di(regs &regs, pins &pins); // A, L
void ins_9E_SBC_di_ind(regs &regs, pins &pins); // A, HL
void ins_9F_SBC_di_di(regs &regs, pins &pins); // A, A
void ins_A0_AND_di_di(regs &regs, pins &pins); // A, B
void ins_A1_AND_di_di(regs &regs, pins &pins); // A, C
void ins_A2_AND_di_di(regs &regs, pins &pins); // A, D
void ins_A3_AND_di_di(regs &regs, pins &pins); // A, E
void ins_A4_AND_di_di(regs &regs, pins &pins); // A, H
void ins_A5_AND_di_di(regs &regs, pins &pins); // A, L
void ins_A6_AND_di_ind(regs &regs, pins &pins); // A, HL
void ins_A7_AND_di_di(regs &regs, pins &pins); // A, A
void ins_A8_XOR_di_di(regs &regs, pins &pins); // A, B
void ins_A9_XOR_di_di(regs &regs, pins &pins); // A, C
void ins_AA_XOR_di_di(regs &regs, pins &pins); // A, D
void ins_AB_XOR_di_di(regs &regs, pins &pins); // A, E
void ins_AC_XOR_di_di(regs &regs, pins &pins); // A, H
void ins_AD_XOR_di_di(regs &regs, pins &pins); // A, L
void ins_AE_XOR_di_ind(regs &regs, pins &pins); // A, HL
void ins_AF_XOR_di_di(regs &regs, pins &pins); // A, A
void ins_B0_OR_di_di(regs &regs, pins &pins); // A, B
void ins_B1_OR_di_di(regs &regs, pins &pins); // A, C
void ins_B2_OR_di_di(regs &regs, pins &pins); // A, D
void ins_B3_OR_di_di(regs &regs, pins &pins); // A, E
void ins_B4_OR_di_di(regs &regs, pins &pins); // A, H
void ins_B5_OR_di_di(regs &regs, pins &pins); // A, L
void ins_B6_OR_di_ind(regs &regs, pins &pins); // A, HL
void ins_B7_OR_di_di(regs &regs, pins &pins); // A, A
void ins_B8_CP_di_di(regs &regs, pins &pins); // A, B
void ins_B9_CP_di_di(regs &regs, pins &pins); // A, C
void ins_BA_CP_di_di(regs &regs, pins &pins); // A, D
void ins_BB_CP_di_di(regs &regs, pins &pins); // A, E
void ins_BC_CP_di_di(regs &regs, pins &pins); // A, H
void ins_BD_CP_di_di(regs &regs, pins &pins); // A, L
void ins_BE_CP_di_ind(regs &regs, pins &pins); // A, HL
void ins_BF_CP_di_di(regs &regs, pins &pins); // A, A
void ins_C0_RET_cond(regs &regs, pins &pins); // regs.F.Z === 0
void ins_C1_POP_di(regs &regs, pins &pins); // BC
void ins_C2_JP_cond_addr(regs &regs, pins &pins); // regs.F.Z === 0
void ins_C3_JP_cond_addr(regs &regs, pins &pins); // 1
void ins_C4_CALL_cond_addr(regs &regs, pins &pins); // regs.F.Z === 0
void ins_C5_PUSH_di(regs &regs, pins &pins); // BC
void ins_C6_ADD_di_da(regs &regs, pins &pins); // A
void ins_C7_RST_imp(regs &regs, pins &pins);
void ins_C8_RET_cond(regs &regs, pins &pins); // regs.F.Z === 1
void ins_C9_RET(regs &regs, pins &pins);
void ins_CA_JP_cond_addr(regs &regs, pins &pins); // regs.F.Z === 1
void ins_CC_CALL_cond_addr(regs &regs, pins &pins); // regs.F.Z === 1
void ins_CD_CALL_cond_addr(regs &regs, pins &pins); // 1
void ins_CE_ADC_di_da(regs &regs, pins &pins); // A
void ins_CF_RST_imp(regs &regs, pins &pins); // 8
void ins_D0_RET_cond(regs &regs, pins &pins); // regs.F.C === 0
void ins_D1_POP_di(regs &regs, pins &pins); // DE
void ins_D2_JP_cond_addr(regs &regs, pins &pins); // regs.F.C === 0
void ins_D3_NONE(regs &regs, pins &pins);
void ins_D4_CALL_cond_addr(regs &regs, pins &pins); // regs.F.C === 0
void ins_D5_PUSH_di(regs &regs, pins &pins); // DE
void ins_D6_SUB_di_da(regs &regs, pins &pins); // A
void ins_D7_RST_imp(regs &regs, pins &pins); // 16
void ins_D8_RET_cond(regs &regs, pins &pins); // regs.F.C === 1
void ins_D9_RETI(regs &regs, pins &pins);
void ins_DA_JP_cond_addr(regs &regs, pins &pins); // regs.F.C === 1
void ins_DB_NONE(regs &regs, pins &pins);
void ins_DC_CALL_cond_addr(regs &regs, pins &pins); // regs.F.C === 1
void ins_DD_NONE(regs &regs, pins &pins);
void ins_DE_SBC_di_da(regs &regs, pins &pins); // A
void ins_DF_RST_imp(regs &regs, pins &pins); // 24
void ins_E0_LDH_addr_di(regs &regs, pins &pins); // A
void ins_E1_POP_di(regs &regs, pins &pins); // HL
void ins_E2_LDH_ind_di(regs &regs, pins &pins); // C, A
void ins_E3_NONE(regs &regs, pins &pins);
void ins_E4_NONE(regs &regs, pins &pins);
void ins_E5_PUSH_di(regs &regs, pins &pins); // HL
void ins_E6_AND_di_da(regs &regs, pins &pins); // A
void ins_E7_RST_imp(regs &regs, pins &pins); // 32
void ins_E8_ADD_di_rel(regs &regs, pins &pins); // SP
void ins_E9_JP_di(regs &regs, pins &pins); // HL
void ins_EA_LD_addr_di(regs &regs, pins &pins); // A
void ins_EB_NONE(regs &regs, pins &pins);
void ins_EC_NONE(regs &regs, pins &pins);
void ins_ED_NONE(regs &regs, pins &pins);
void ins_EE_XOR_di_da(regs &regs, pins &pins); // A
void ins_EF_RST_imp(regs &regs, pins &pins); // 40
void ins_F0_LDH_di_addr(regs &regs, pins &pins); // A
void ins_F1_POP_di_AF(regs &regs, pins &pins); // AF
void ins_F2_LDH_di_ind(regs &regs, pins &pins); // A, C
void ins_F3_DI(regs &regs, pins &pins);
void ins_F4_NONE(regs &regs, pins &pins);
void ins_F5_PUSH_di(regs &regs, pins &pins); // AF
void ins_F6_OR_di_da(regs &regs, pins &pins); // A
void ins_F7_RST_imp(regs &regs, pins &pins); // 48
void ins_F8_LD_di_di_rel(regs &regs, pins &pins); // HL, SP
void ins_F9_LD16_di_di(regs &regs, pins &pins); // SP, HL
void ins_FA_LD_di_addr(regs &regs, pins &pins); // A
void ins_FB_EI(regs &regs, pins &pins);
void ins_FC_NONE(regs &regs, pins &pins);
void ins_FD_NONE(regs &regs, pins &pins);
void ins_FE_CP_di_da(regs &regs, pins &pins); // A
void ins_FF_RST_imp(regs &regs, pins &pins); // 56
void ins_100_S_IRQ(regs &regs, pins &pins);
void ins_101_RESET(regs &regs, pins &pins);
void ins_CB00_RLC_di(regs &regs, pins &pins); // B
void ins_CB01_RLC_di(regs &regs, pins &pins); // C
void ins_CB02_RLC_di(regs &regs, pins &pins); // D
void ins_CB03_RLC_di(regs &regs, pins &pins); // E
void ins_CB04_RLC_di(regs &regs, pins &pins); // H
void ins_CB05_RLC_di(regs &regs, pins &pins); // L
void ins_CB06_RLC_ind(regs &regs, pins &pins); // HL
void ins_CB07_RLC_di(regs &regs, pins &pins); // A
void ins_CB08_RRC_di(regs &regs, pins &pins); // B
void ins_CB09_RRC_di(regs &regs, pins &pins); // C
void ins_CB0A_RRC_di(regs &regs, pins &pins); // D
void ins_CB0B_RRC_di(regs &regs, pins &pins); // E
void ins_CB0C_RRC_di(regs &regs, pins &pins); // H
void ins_CB0D_RRC_di(regs &regs, pins &pins); // L
void ins_CB0E_RRC_ind(regs &regs, pins &pins); // HL
void ins_CB0F_RRC_di(regs &regs, pins &pins); // A
void ins_CB10_RL_di(regs &regs, pins &pins); // B
void ins_CB11_RL_di(regs &regs, pins &pins); // C
void ins_CB12_RL_di(regs &regs, pins &pins); // D
void ins_CB13_RL_di(regs &regs, pins &pins); // E
void ins_CB14_RL_di(regs &regs, pins &pins); // H
void ins_CB15_RL_di(regs &regs, pins &pins); // L
void ins_CB16_RL_ind(regs &regs, pins &pins); // HL
void ins_CB17_RL_di(regs &regs, pins &pins); // A
void ins_CB18_RR_di(regs &regs, pins &pins); // B
void ins_CB19_RR_di(regs &regs, pins &pins); // C
void ins_CB1A_RR_di(regs &regs, pins &pins); // D
void ins_CB1B_RR_di(regs &regs, pins &pins); // E
void ins_CB1C_RR_di(regs &regs, pins &pins); // H
void ins_CB1D_RR_di(regs &regs, pins &pins); // L
void ins_CB1E_RR_ind(regs &regs, pins &pins); // HL
void ins_CB1F_RR_di(regs &regs, pins &pins); // A
void ins_CB20_SLA_di(regs &regs, pins &pins); // B
void ins_CB21_SLA_di(regs &regs, pins &pins); // C
void ins_CB22_SLA_di(regs &regs, pins &pins); // D
void ins_CB23_SLA_di(regs &regs, pins &pins); // E
void ins_CB24_SLA_di(regs &regs, pins &pins); // H
void ins_CB25_SLA_di(regs &regs, pins &pins); // L
void ins_CB26_SLA_ind(regs &regs, pins &pins); // HL
void ins_CB27_SLA_di(regs &regs, pins &pins); // A
void ins_CB28_SRA_di(regs &regs, pins &pins); // B
void ins_CB29_SRA_di(regs &regs, pins &pins); // C
void ins_CB2A_SRA_di(regs &regs, pins &pins); // D
void ins_CB2B_SRA_di(regs &regs, pins &pins); // E
void ins_CB2C_SRA_di(regs &regs, pins &pins); // H
void ins_CB2D_SRA_di(regs &regs, pins &pins); // L
void ins_CB2E_SRA_ind(regs &regs, pins &pins); // HL
void ins_CB2F_SRA_di(regs &regs, pins &pins); // A
void ins_CB30_SWAP_di(regs &regs, pins &pins); // B
void ins_CB31_SWAP_di(regs &regs, pins &pins); // C
void ins_CB32_SWAP_di(regs &regs, pins &pins); // D
void ins_CB33_SWAP_di(regs &regs, pins &pins); // E
void ins_CB34_SWAP_di(regs &regs, pins &pins); // H
void ins_CB35_SWAP_di(regs &regs, pins &pins); // L
void ins_CB36_SWAP_ind(regs &regs, pins &pins); // HL
void ins_CB37_SWAP_di(regs &regs, pins &pins); // A
void ins_CB38_SRL_di(regs &regs, pins &pins); // B
void ins_CB39_SRL_di(regs &regs, pins &pins); // C
void ins_CB3A_SRL_di(regs &regs, pins &pins); // D
void ins_CB3B_SRL_di(regs &regs, pins &pins); // E
void ins_CB3C_SRL_di(regs &regs, pins &pins); // H
void ins_CB3D_SRL_di(regs &regs, pins &pins); // L
void ins_CB3E_SRL_ind(regs &regs, pins &pins); // HL
void ins_CB3F_SRL_di(regs &regs, pins &pins); // A
void ins_CB40_BIT_idx_di(regs &regs, pins &pins); // B
void ins_CB41_BIT_idx_di(regs &regs, pins &pins); // C
void ins_CB42_BIT_idx_di(regs &regs, pins &pins); // D
void ins_CB43_BIT_idx_di(regs &regs, pins &pins); // E
void ins_CB44_BIT_idx_di(regs &regs, pins &pins); // H
void ins_CB45_BIT_idx_di(regs &regs, pins &pins); // L
void ins_CB46_BIT_idx_ind(regs &regs, pins &pins); // HL
void ins_CB47_BIT_idx_di(regs &regs, pins &pins); // A
void ins_CB48_BIT_idx_di(regs &regs, pins &pins); // 1, B
void ins_CB49_BIT_idx_di(regs &regs, pins &pins); // 1, C
void ins_CB4A_BIT_idx_di(regs &regs, pins &pins); // 1, D
void ins_CB4B_BIT_idx_di(regs &regs, pins &pins); // 1, E
void ins_CB4C_BIT_idx_di(regs &regs, pins &pins); // 1, H
void ins_CB4D_BIT_idx_di(regs &regs, pins &pins); // 1, L
void ins_CB4E_BIT_idx_ind(regs &regs, pins &pins); // 1, HL
void ins_CB4F_BIT_idx_di(regs &regs, pins &pins); // 1, A
void ins_CB50_BIT_idx_di(regs &regs, pins &pins); // 2, B
void ins_CB51_BIT_idx_di(regs &regs, pins &pins); // 2, C
void ins_CB52_BIT_idx_di(regs &regs, pins &pins); // 2, D
void ins_CB53_BIT_idx_di(regs &regs, pins &pins); // 2, E
void ins_CB54_BIT_idx_di(regs &regs, pins &pins); // 2, H
void ins_CB55_BIT_idx_di(regs &regs, pins &pins); // 2, L
void ins_CB56_BIT_idx_ind(regs &regs, pins &pins); // 2, HL
void ins_CB57_BIT_idx_di(regs &regs, pins &pins); // 2, A
void ins_CB58_BIT_idx_di(regs &regs, pins &pins); // 3, B
void ins_CB59_BIT_idx_di(regs &regs, pins &pins); // 3, C
void ins_CB5A_BIT_idx_di(regs &regs, pins &pins); // 3, D
void ins_CB5B_BIT_idx_di(regs &regs, pins &pins); // 3, E
void ins_CB5C_BIT_idx_di(regs &regs, pins &pins); // 3, H
void ins_CB5D_BIT_idx_di(regs &regs, pins &pins); // 3, L
void ins_CB5E_BIT_idx_ind(regs &regs, pins &pins); // 3, HL
void ins_CB5F_BIT_idx_di(regs &regs, pins &pins); // 3, A
void ins_CB60_BIT_idx_di(regs &regs, pins &pins); // 4, B
void ins_CB61_BIT_idx_di(regs &regs, pins &pins); // 4, C
void ins_CB62_BIT_idx_di(regs &regs, pins &pins); // 4, D
void ins_CB63_BIT_idx_di(regs &regs, pins &pins); // 4, E
void ins_CB64_BIT_idx_di(regs &regs, pins &pins); // 4, H
void ins_CB65_BIT_idx_di(regs &regs, pins &pins); // 4, L
void ins_CB66_BIT_idx_ind(regs &regs, pins &pins); // 4, HL
void ins_CB67_BIT_idx_di(regs &regs, pins &pins); // 4, A
void ins_CB68_BIT_idx_di(regs &regs, pins &pins); // 5, B
void ins_CB69_BIT_idx_di(regs &regs, pins &pins); // 5, C
void ins_CB6A_BIT_idx_di(regs &regs, pins &pins); // 5, D
void ins_CB6B_BIT_idx_di(regs &regs, pins &pins); // 5, E
void ins_CB6C_BIT_idx_di(regs &regs, pins &pins); // 5, H
void ins_CB6D_BIT_idx_di(regs &regs, pins &pins); // 5, L
void ins_CB6E_BIT_idx_ind(regs &regs, pins &pins); // 5, HL
void ins_CB6F_BIT_idx_di(regs &regs, pins &pins); // 5, A
void ins_CB70_BIT_idx_di(regs &regs, pins &pins); // 6, B
void ins_CB71_BIT_idx_di(regs &regs, pins &pins); // 6, C
void ins_CB72_BIT_idx_di(regs &regs, pins &pins); // 6, D
void ins_CB73_BIT_idx_di(regs &regs, pins &pins); // 6, E
void ins_CB74_BIT_idx_di(regs &regs, pins &pins); // 6, H
void ins_CB75_BIT_idx_di(regs &regs, pins &pins); // 6, L
void ins_CB76_BIT_idx_ind(regs &regs, pins &pins); // 6, HL
void ins_CB77_BIT_idx_di(regs &regs, pins &pins); // 6, A
void ins_CB78_BIT_idx_di(regs &regs, pins &pins); // 7, B
void ins_CB79_BIT_idx_di(regs &regs, pins &pins); // 7, C
void ins_CB7A_BIT_idx_di(regs &regs, pins &pins); // 7, D
void ins_CB7B_BIT_idx_di(regs &regs, pins &pins); // 7, E
void ins_CB7C_BIT_idx_di(regs &regs, pins &pins); // 7, H
void ins_CB7D_BIT_idx_di(regs &regs, pins &pins); // 7, L
void ins_CB7E_BIT_idx_ind(regs &regs, pins &pins); // 7, HL
void ins_CB7F_BIT_idx_di(regs &regs, pins &pins); // 7, A
void ins_CB80_RES_idx_di(regs &regs, pins &pins); // B
void ins_CB81_RES_idx_di(regs &regs, pins &pins); // C
void ins_CB82_RES_idx_di(regs &regs, pins &pins); // D
void ins_CB83_RES_idx_di(regs &regs, pins &pins); // E
void ins_CB84_RES_idx_di(regs &regs, pins &pins); // H
void ins_CB85_RES_idx_di(regs &regs, pins &pins); // L
void ins_CB86_RES_idx_ind(regs &regs, pins &pins); // HL
void ins_CB87_RES_idx_di(regs &regs, pins &pins); // A
void ins_CB88_RES_idx_di(regs &regs, pins &pins); // 1, B
void ins_CB89_RES_idx_di(regs &regs, pins &pins); // 1, C
void ins_CB8A_RES_idx_di(regs &regs, pins &pins); // 1, D
void ins_CB8B_RES_idx_di(regs &regs, pins &pins); // 1, E
void ins_CB8C_RES_idx_di(regs &regs, pins &pins); // 1, H
void ins_CB8D_RES_idx_di(regs &regs, pins &pins); // 1, L
void ins_CB8E_RES_idx_ind(regs &regs, pins &pins); // 1, HL
void ins_CB8F_RES_idx_di(regs &regs, pins &pins); // 1, A
void ins_CB90_RES_idx_di(regs &regs, pins &pins); // 2, B
void ins_CB91_RES_idx_di(regs &regs, pins &pins); // 2, C
void ins_CB92_RES_idx_di(regs &regs, pins &pins); // 2, D
void ins_CB93_RES_idx_di(regs &regs, pins &pins); // 2, E
void ins_CB94_RES_idx_di(regs &regs, pins &pins); // 2, H
void ins_CB95_RES_idx_di(regs &regs, pins &pins); // 2, L
void ins_CB96_RES_idx_ind(regs &regs, pins &pins); // 2, HL
void ins_CB97_RES_idx_di(regs &regs, pins &pins); // 2, A
void ins_CB98_RES_idx_di(regs &regs, pins &pins); // 3, B
void ins_CB99_RES_idx_di(regs &regs, pins &pins); // 3, C
void ins_CB9A_RES_idx_di(regs &regs, pins &pins); // 3, D
void ins_CB9B_RES_idx_di(regs &regs, pins &pins); // 3, E
void ins_CB9C_RES_idx_di(regs &regs, pins &pins); // 3, H
void ins_CB9D_RES_idx_di(regs &regs, pins &pins); // 3, L
void ins_CB9E_RES_idx_ind(regs &regs, pins &pins); // 3, HL
void ins_CB9F_RES_idx_di(regs &regs, pins &pins); // 3, A
void ins_CBA0_RES_idx_di(regs &regs, pins &pins); // 4, B
void ins_CBA1_RES_idx_di(regs &regs, pins &pins); // 4, C
void ins_CBA2_RES_idx_di(regs &regs, pins &pins); // 4, D
void ins_CBA3_RES_idx_di(regs &regs, pins &pins); // 4, E
void ins_CBA4_RES_idx_di(regs &regs, pins &pins); // 4, H
void ins_CBA5_RES_idx_di(regs &regs, pins &pins); // 4, L
void ins_CBA6_RES_idx_ind(regs &regs, pins &pins); // 4, HL
void ins_CBA7_RES_idx_di(regs &regs, pins &pins); // 4, A
void ins_CBA8_RES_idx_di(regs &regs, pins &pins); // 5, B
void ins_CBA9_RES_idx_di(regs &regs, pins &pins); // 5, C
void ins_CBAA_RES_idx_di(regs &regs, pins &pins); // 5, D
void ins_CBAB_RES_idx_di(regs &regs, pins &pins); // 5, E
void ins_CBAC_RES_idx_di(regs &regs, pins &pins); // 5, H
void ins_CBAD_RES_idx_di(regs &regs, pins &pins); // 5, L
void ins_CBAE_RES_idx_ind(regs &regs, pins &pins); // 5, HL
void ins_CBAF_RES_idx_di(regs &regs, pins &pins); // 5, A
void ins_CBB0_RES_idx_di(regs &regs, pins &pins); // 6, B
void ins_CBB1_RES_idx_di(regs &regs, pins &pins); // 6, C
void ins_CBB2_RES_idx_di(regs &regs, pins &pins); // 6, D
void ins_CBB3_RES_idx_di(regs &regs, pins &pins); // 6, E
void ins_CBB4_RES_idx_di(regs &regs, pins &pins); // 6, H
void ins_CBB5_RES_idx_di(regs &regs, pins &pins); // 6, L
void ins_CBB6_RES_idx_ind(regs &regs, pins &pins); // 6, HL
void ins_CBB7_RES_idx_di(regs &regs, pins &pins); // 6, A
void ins_CBB8_RES_idx_di(regs &regs, pins &pins); // 7, B
void ins_CBB9_RES_idx_di(regs &regs, pins &pins); // 7, C
void ins_CBBA_RES_idx_di(regs &regs, pins &pins); // 7, D
void ins_CBBB_RES_idx_di(regs &regs, pins &pins); // 7, E
void ins_CBBC_RES_idx_di(regs &regs, pins &pins); // 7, H
void ins_CBBD_RES_idx_di(regs &regs, pins &pins); // 7, L
void ins_CBBE_RES_idx_ind(regs &regs, pins &pins); // 7, HL
void ins_CBBF_RES_idx_di(regs &regs, pins &pins); // 7, A
void ins_CBC0_SET_idx_di(regs &regs, pins &pins); // B
void ins_CBC1_SET_idx_di(regs &regs, pins &pins); // C
void ins_CBC2_SET_idx_di(regs &regs, pins &pins); // D
void ins_CBC3_SET_idx_di(regs &regs, pins &pins); // E
void ins_CBC4_SET_idx_di(regs &regs, pins &pins); // H
void ins_CBC5_SET_idx_di(regs &regs, pins &pins); // L
void ins_CBC6_SET_idx_ind(regs &regs, pins &pins); // HL
void ins_CBC7_SET_idx_di(regs &regs, pins &pins); // A
void ins_CBC8_SET_idx_di(regs &regs, pins &pins); // 1, B
void ins_CBC9_SET_idx_di(regs &regs, pins &pins); // 1, C
void ins_CBCA_SET_idx_di(regs &regs, pins &pins); // 1, D
void ins_CBCB_SET_idx_di(regs &regs, pins &pins); // 1, E
void ins_CBCC_SET_idx_di(regs &regs, pins &pins); // 1, H
void ins_CBCD_SET_idx_di(regs &regs, pins &pins); // 1, L
void ins_CBCE_SET_idx_ind(regs &regs, pins &pins); // 1, HL
void ins_CBCF_SET_idx_di(regs &regs, pins &pins); // 1, A
void ins_CBD0_SET_idx_di(regs &regs, pins &pins); // 2, B
void ins_CBD1_SET_idx_di(regs &regs, pins &pins); // 2, C
void ins_CBD2_SET_idx_di(regs &regs, pins &pins); // 2, D
void ins_CBD3_SET_idx_di(regs &regs, pins &pins); // 2, E
void ins_CBD4_SET_idx_di(regs &regs, pins &pins); // 2, H
void ins_CBD5_SET_idx_di(regs &regs, pins &pins); // 2, L
void ins_CBD6_SET_idx_ind(regs &regs, pins &pins); // 2, HL
void ins_CBD7_SET_idx_di(regs &regs, pins &pins); // 2, A
void ins_CBD8_SET_idx_di(regs &regs, pins &pins); // 3, B
void ins_CBD9_SET_idx_di(regs &regs, pins &pins); // 3, C
void ins_CBDA_SET_idx_di(regs &regs, pins &pins); // 3, D
void ins_CBDB_SET_idx_di(regs &regs, pins &pins); // 3, E
void ins_CBDC_SET_idx_di(regs &regs, pins &pins); // 3, H
void ins_CBDD_SET_idx_di(regs &regs, pins &pins); // 3, L
void ins_CBDE_SET_idx_ind(regs &regs, pins &pins); // 3, HL
void ins_CBDF_SET_idx_di(regs &regs, pins &pins); // 3, A
void ins_CBE0_SET_idx_di(regs &regs, pins &pins); // 4, B
void ins_CBE1_SET_idx_di(regs &regs, pins &pins); // 4, C
void ins_CBE2_SET_idx_di(regs &regs, pins &pins); // 4, D
void ins_CBE3_SET_idx_di(regs &regs, pins &pins); // 4, E
void ins_CBE4_SET_idx_di(regs &regs, pins &pins); // 4, H
void ins_CBE5_SET_idx_di(regs &regs, pins &pins); // 4, L
void ins_CBE6_SET_idx_ind(regs &regs, pins &pins); // 4, HL
void ins_CBE7_SET_idx_di(regs &regs, pins &pins); // 4, A
void ins_CBE8_SET_idx_di(regs &regs, pins &pins); // 5, B
void ins_CBE9_SET_idx_di(regs &regs, pins &pins); // 5, C
void ins_CBEA_SET_idx_di(regs &regs, pins &pins); // 5, D
void ins_CBEB_SET_idx_di(regs &regs, pins &pins); // 5, E
void ins_CBEC_SET_idx_di(regs &regs, pins &pins); // 5, H
void ins_CBED_SET_idx_di(regs &regs, pins &pins); // 5, L
void ins_CBEE_SET_idx_ind(regs &regs, pins &pins); // 5, HL
void ins_CBEF_SET_idx_di(regs &regs, pins &pins); // 5, A
void ins_CBF0_SET_idx_di(regs &regs, pins &pins); // 6, B
void ins_CBF1_SET_idx_di(regs &regs, pins &pins); // 6, C
void ins_CBF2_SET_idx_di(regs &regs, pins &pins); // 6, D
void ins_CBF3_SET_idx_di(regs &regs, pins &pins); // 6, E
void ins_CBF4_SET_idx_di(regs &regs, pins &pins); // 6, H
void ins_CBF5_SET_idx_di(regs &regs, pins &pins); // 6, L
void ins_CBF6_SET_idx_ind(regs &regs, pins &pins); // 6, HL
void ins_CBF7_SET_idx_di(regs &regs, pins &pins); // 6, A
void ins_CBF8_SET_idx_di(regs &regs, pins &pins); // 7, B
void ins_CBF9_SET_idx_di(regs &regs, pins &pins); // 7, C
void ins_CBFA_SET_idx_di(regs &regs, pins &pins); // 7, D
void ins_CBFB_SET_idx_di(regs &regs, pins &pins); // 7, E
void ins_CBFC_SET_idx_di(regs &regs, pins &pins); // 7, H
void ins_CBFD_SET_idx_di(regs &regs, pins &pins); // 7, L
void ins_CBFE_SET_idx_ind(regs &regs, pins &pins); // 7, HL
void ins_CBFF_SET_idx_di(regs &regs, pins &pins); // 7, A

}