#ifndef _JSMOOCH_SM83_OPCODES_H
#define _JSMOOCH_SM83_OPCODES_H

#include "sm83_misc.h"

// This file generated by sm83_opcodes.js in JSMoo

void SM83_ins_00_NOP(struct SM83_regs* regs, struct SM83_pins* pins);
void SM83_ins_01_LD16_di_da(struct SM83_regs* regs, struct SM83_pins* pins); // BC
void SM83_ins_02_LD_ind_di(struct SM83_regs* regs, struct SM83_pins* pins); // BC, A
void SM83_ins_03_INC16_di(struct SM83_regs* regs, struct SM83_pins* pins); // BC
void SM83_ins_04_INC_di(struct SM83_regs* regs, struct SM83_pins* pins); // B
void SM83_ins_05_DEC_di(struct SM83_regs* regs, struct SM83_pins* pins); // B
void SM83_ins_06_LD_di_da(struct SM83_regs* regs, struct SM83_pins* pins); // B
void SM83_ins_07_RLCA(struct SM83_regs* regs, struct SM83_pins* pins);
void SM83_ins_08_LD16_addr_di(struct SM83_regs* regs, struct SM83_pins* pins); // SP
void SM83_ins_09_ADD16_di_di(struct SM83_regs* regs, struct SM83_pins* pins); // HL, BC
void SM83_ins_0A_LD_di_ind(struct SM83_regs* regs, struct SM83_pins* pins); // A, BC
void SM83_ins_0B_DEC16_di(struct SM83_regs* regs, struct SM83_pins* pins); // BC
void SM83_ins_0C_INC_di(struct SM83_regs* regs, struct SM83_pins* pins); // C
void SM83_ins_0D_DEC_di(struct SM83_regs* regs, struct SM83_pins* pins); // C
void SM83_ins_0E_LD_di_da(struct SM83_regs* regs, struct SM83_pins* pins); // C
void SM83_ins_0F_RRCA(struct SM83_regs* regs, struct SM83_pins* pins);
void SM83_ins_10_STOP(struct SM83_regs* regs, struct SM83_pins* pins);
void SM83_ins_11_LD16_di_da(struct SM83_regs* regs, struct SM83_pins* pins); // DE
void SM83_ins_12_LD_ind_di(struct SM83_regs* regs, struct SM83_pins* pins); // DE, A
void SM83_ins_13_INC16_di(struct SM83_regs* regs, struct SM83_pins* pins); // DE
void SM83_ins_14_INC_di(struct SM83_regs* regs, struct SM83_pins* pins); // D
void SM83_ins_15_DEC_di(struct SM83_regs* regs, struct SM83_pins* pins); // D
void SM83_ins_16_LD_di_da(struct SM83_regs* regs, struct SM83_pins* pins); // D
void SM83_ins_17_RLA(struct SM83_regs* regs, struct SM83_pins* pins);
void SM83_ins_18_JR_cond_rel(struct SM83_regs* regs, struct SM83_pins* pins); // 1
void SM83_ins_19_ADD16_di_di(struct SM83_regs* regs, struct SM83_pins* pins); // HL, DE
void SM83_ins_1A_LD_di_ind(struct SM83_regs* regs, struct SM83_pins* pins); // A, DE
void SM83_ins_1B_DEC16_di(struct SM83_regs* regs, struct SM83_pins* pins); // DE
void SM83_ins_1C_INC_di(struct SM83_regs* regs, struct SM83_pins* pins); // E
void SM83_ins_1D_DEC_di(struct SM83_regs* regs, struct SM83_pins* pins); // E
void SM83_ins_1E_LD_di_da(struct SM83_regs* regs, struct SM83_pins* pins); // E
void SM83_ins_1F_RRA(struct SM83_regs* regs, struct SM83_pins* pins);
void SM83_ins_20_JR_cond_rel(struct SM83_regs* regs, struct SM83_pins* pins); // regs.F.Z === 0
void SM83_ins_21_LD16_di_da(struct SM83_regs* regs, struct SM83_pins* pins); // HL
void SM83_ins_22_LD_ind_inc_di(struct SM83_regs* regs, struct SM83_pins* pins); // HL, A
void SM83_ins_23_INC16_di(struct SM83_regs* regs, struct SM83_pins* pins); // HL
void SM83_ins_24_INC_di(struct SM83_regs* regs, struct SM83_pins* pins); // H
void SM83_ins_25_DEC_di(struct SM83_regs* regs, struct SM83_pins* pins); // H
void SM83_ins_26_LD_di_da(struct SM83_regs* regs, struct SM83_pins* pins); // H
void SM83_ins_27_DAA(struct SM83_regs* regs, struct SM83_pins* pins);
void SM83_ins_28_JR_cond_rel(struct SM83_regs* regs, struct SM83_pins* pins); // regs.F.Z === 1
void SM83_ins_29_ADD16_di_di(struct SM83_regs* regs, struct SM83_pins* pins); // HL, HL
void SM83_ins_2A_LD_di_ind_inc(struct SM83_regs* regs, struct SM83_pins* pins); // A, HL
void SM83_ins_2B_DEC16_di(struct SM83_regs* regs, struct SM83_pins* pins); // HL
void SM83_ins_2C_INC_di(struct SM83_regs* regs, struct SM83_pins* pins); // L
void SM83_ins_2D_DEC_di(struct SM83_regs* regs, struct SM83_pins* pins); // L
void SM83_ins_2E_LD_di_da(struct SM83_regs* regs, struct SM83_pins* pins); // L
void SM83_ins_2F_CPL(struct SM83_regs* regs, struct SM83_pins* pins);
void SM83_ins_30_JR_cond_rel(struct SM83_regs* regs, struct SM83_pins* pins); // regs.F.C === 0
void SM83_ins_31_LD16_di_da(struct SM83_regs* regs, struct SM83_pins* pins); // SP
void SM83_ins_32_LD_ind_dec_di(struct SM83_regs* regs, struct SM83_pins* pins); // HL, A
void SM83_ins_33_INC16_di(struct SM83_regs* regs, struct SM83_pins* pins); // SP
void SM83_ins_34_INC_ind(struct SM83_regs* regs, struct SM83_pins* pins); // HL
void SM83_ins_35_DEC_ind(struct SM83_regs* regs, struct SM83_pins* pins); // HL
void SM83_ins_36_LD_ind_da(struct SM83_regs* regs, struct SM83_pins* pins); // HL
void SM83_ins_37_SCF(struct SM83_regs* regs, struct SM83_pins* pins);
void SM83_ins_38_JR_cond_rel(struct SM83_regs* regs, struct SM83_pins* pins); // regs.F.C === 1
void SM83_ins_39_ADD16_di_di(struct SM83_regs* regs, struct SM83_pins* pins); // HL, SP
void SM83_ins_3A_LD_di_ind_dec(struct SM83_regs* regs, struct SM83_pins* pins); // A, HL
void SM83_ins_3B_DEC16_di(struct SM83_regs* regs, struct SM83_pins* pins); // SP
void SM83_ins_3C_INC_di(struct SM83_regs* regs, struct SM83_pins* pins); // A
void SM83_ins_3D_DEC_di(struct SM83_regs* regs, struct SM83_pins* pins); // A
void SM83_ins_3E_LD_di_da(struct SM83_regs* regs, struct SM83_pins* pins); // A
void SM83_ins_3F_CCF(struct SM83_regs* regs, struct SM83_pins* pins);
void SM83_ins_40_LD_di_di(struct SM83_regs* regs, struct SM83_pins* pins); // B, B
void SM83_ins_41_LD_di_di(struct SM83_regs* regs, struct SM83_pins* pins); // B, C
void SM83_ins_42_LD_di_di(struct SM83_regs* regs, struct SM83_pins* pins); // B, D
void SM83_ins_43_LD_di_di(struct SM83_regs* regs, struct SM83_pins* pins); // B, E
void SM83_ins_44_LD_di_di(struct SM83_regs* regs, struct SM83_pins* pins); // B, H
void SM83_ins_45_LD_di_di(struct SM83_regs* regs, struct SM83_pins* pins); // B, L
void SM83_ins_46_LD_di_ind(struct SM83_regs* regs, struct SM83_pins* pins); // B, HL
void SM83_ins_47_LD_di_di(struct SM83_regs* regs, struct SM83_pins* pins); // B, A
void SM83_ins_48_LD_di_di(struct SM83_regs* regs, struct SM83_pins* pins); // C, B
void SM83_ins_49_LD_di_di(struct SM83_regs* regs, struct SM83_pins* pins); // C, C
void SM83_ins_4A_LD_di_di(struct SM83_regs* regs, struct SM83_pins* pins); // C, D
void SM83_ins_4B_LD_di_di(struct SM83_regs* regs, struct SM83_pins* pins); // C, E
void SM83_ins_4C_LD_di_di(struct SM83_regs* regs, struct SM83_pins* pins); // C, H
void SM83_ins_4D_LD_di_di(struct SM83_regs* regs, struct SM83_pins* pins); // C, L
void SM83_ins_4E_LD_di_ind(struct SM83_regs* regs, struct SM83_pins* pins); // C, HL
void SM83_ins_4F_LD_di_di(struct SM83_regs* regs, struct SM83_pins* pins); // C, A
void SM83_ins_50_LD_di_di(struct SM83_regs* regs, struct SM83_pins* pins); // D, B
void SM83_ins_51_LD_di_di(struct SM83_regs* regs, struct SM83_pins* pins); // D, C
void SM83_ins_52_LD_di_di(struct SM83_regs* regs, struct SM83_pins* pins); // D, D
void SM83_ins_53_LD_di_di(struct SM83_regs* regs, struct SM83_pins* pins); // D, E
void SM83_ins_54_LD_di_di(struct SM83_regs* regs, struct SM83_pins* pins); // D, H
void SM83_ins_55_LD_di_di(struct SM83_regs* regs, struct SM83_pins* pins); // D, L
void SM83_ins_56_LD_di_ind(struct SM83_regs* regs, struct SM83_pins* pins); // D, HL
void SM83_ins_57_LD_di_di(struct SM83_regs* regs, struct SM83_pins* pins); // D, A
void SM83_ins_58_LD_di_di(struct SM83_regs* regs, struct SM83_pins* pins); // E, B
void SM83_ins_59_LD_di_di(struct SM83_regs* regs, struct SM83_pins* pins); // E, C
void SM83_ins_5A_LD_di_di(struct SM83_regs* regs, struct SM83_pins* pins); // E, D
void SM83_ins_5B_LD_di_di(struct SM83_regs* regs, struct SM83_pins* pins); // E, E
void SM83_ins_5C_LD_di_di(struct SM83_regs* regs, struct SM83_pins* pins); // E, H
void SM83_ins_5D_LD_di_di(struct SM83_regs* regs, struct SM83_pins* pins); // E, L
void SM83_ins_5E_LD_di_ind(struct SM83_regs* regs, struct SM83_pins* pins); // E, HL
void SM83_ins_5F_LD_di_di(struct SM83_regs* regs, struct SM83_pins* pins); // E, A
void SM83_ins_60_LD_di_di(struct SM83_regs* regs, struct SM83_pins* pins); // H, B
void SM83_ins_61_LD_di_di(struct SM83_regs* regs, struct SM83_pins* pins); // H, C
void SM83_ins_62_LD_di_di(struct SM83_regs* regs, struct SM83_pins* pins); // H, D
void SM83_ins_63_LD_di_di(struct SM83_regs* regs, struct SM83_pins* pins); // H, E
void SM83_ins_64_LD_di_di(struct SM83_regs* regs, struct SM83_pins* pins); // H, H
void SM83_ins_65_LD_di_di(struct SM83_regs* regs, struct SM83_pins* pins); // H, L
void SM83_ins_66_LD_di_ind(struct SM83_regs* regs, struct SM83_pins* pins); // H, HL
void SM83_ins_67_LD_di_di(struct SM83_regs* regs, struct SM83_pins* pins); // H, A
void SM83_ins_68_LD_di_di(struct SM83_regs* regs, struct SM83_pins* pins); // L, B
void SM83_ins_69_LD_di_di(struct SM83_regs* regs, struct SM83_pins* pins); // L, C
void SM83_ins_6A_LD_di_di(struct SM83_regs* regs, struct SM83_pins* pins); // L, D
void SM83_ins_6B_LD_di_di(struct SM83_regs* regs, struct SM83_pins* pins); // L, E
void SM83_ins_6C_LD_di_di(struct SM83_regs* regs, struct SM83_pins* pins); // L, H
void SM83_ins_6D_LD_di_di(struct SM83_regs* regs, struct SM83_pins* pins); // L, L
void SM83_ins_6E_LD_di_ind(struct SM83_regs* regs, struct SM83_pins* pins); // L, HL
void SM83_ins_6F_LD_di_di(struct SM83_regs* regs, struct SM83_pins* pins); // L, A
void SM83_ins_70_LD_ind_di(struct SM83_regs* regs, struct SM83_pins* pins); // HL, B
void SM83_ins_71_LD_ind_di(struct SM83_regs* regs, struct SM83_pins* pins); // HL, C
void SM83_ins_72_LD_ind_di(struct SM83_regs* regs, struct SM83_pins* pins); // HL, D
void SM83_ins_73_LD_ind_di(struct SM83_regs* regs, struct SM83_pins* pins); // HL, E
void SM83_ins_74_LD_ind_di(struct SM83_regs* regs, struct SM83_pins* pins); // HL, H
void SM83_ins_75_LD_ind_di(struct SM83_regs* regs, struct SM83_pins* pins); // HL, L
void SM83_ins_76_HALT(struct SM83_regs* regs, struct SM83_pins* pins);
void SM83_ins_77_LD_ind_di(struct SM83_regs* regs, struct SM83_pins* pins); // HL, A
void SM83_ins_78_LD_di_di(struct SM83_regs* regs, struct SM83_pins* pins); // A, B
void SM83_ins_79_LD_di_di(struct SM83_regs* regs, struct SM83_pins* pins); // A, C
void SM83_ins_7A_LD_di_di(struct SM83_regs* regs, struct SM83_pins* pins); // A, D
void SM83_ins_7B_LD_di_di(struct SM83_regs* regs, struct SM83_pins* pins); // A, E
void SM83_ins_7C_LD_di_di(struct SM83_regs* regs, struct SM83_pins* pins); // A, H
void SM83_ins_7D_LD_di_di(struct SM83_regs* regs, struct SM83_pins* pins); // A, L
void SM83_ins_7E_LD_di_ind(struct SM83_regs* regs, struct SM83_pins* pins); // A, HL
void SM83_ins_7F_LD_di_di(struct SM83_regs* regs, struct SM83_pins* pins); // A, A
void SM83_ins_80_ADD_di_di(struct SM83_regs* regs, struct SM83_pins* pins); // A, B
void SM83_ins_81_ADD_di_di(struct SM83_regs* regs, struct SM83_pins* pins); // A, C
void SM83_ins_82_ADD_di_di(struct SM83_regs* regs, struct SM83_pins* pins); // A, D
void SM83_ins_83_ADD_di_di(struct SM83_regs* regs, struct SM83_pins* pins); // A, E
void SM83_ins_84_ADD_di_di(struct SM83_regs* regs, struct SM83_pins* pins); // A, H
void SM83_ins_85_ADD_di_di(struct SM83_regs* regs, struct SM83_pins* pins); // A, L
void SM83_ins_86_ADD_di_ind(struct SM83_regs* regs, struct SM83_pins* pins); // A, HL
void SM83_ins_87_ADD_di_di(struct SM83_regs* regs, struct SM83_pins* pins); // A, A
void SM83_ins_88_ADC_di_di(struct SM83_regs* regs, struct SM83_pins* pins); // A, B
void SM83_ins_89_ADC_di_di(struct SM83_regs* regs, struct SM83_pins* pins); // A, C
void SM83_ins_8A_ADC_di_di(struct SM83_regs* regs, struct SM83_pins* pins); // A, D
void SM83_ins_8B_ADC_di_di(struct SM83_regs* regs, struct SM83_pins* pins); // A, E
void SM83_ins_8C_ADC_di_di(struct SM83_regs* regs, struct SM83_pins* pins); // A, H
void SM83_ins_8D_ADC_di_di(struct SM83_regs* regs, struct SM83_pins* pins); // A, L
void SM83_ins_8E_ADC_di_ind(struct SM83_regs* regs, struct SM83_pins* pins); // A, HL
void SM83_ins_8F_ADC_di_di(struct SM83_regs* regs, struct SM83_pins* pins); // A, A
void SM83_ins_90_SUB_di_di(struct SM83_regs* regs, struct SM83_pins* pins); // A, B
void SM83_ins_91_SUB_di_di(struct SM83_regs* regs, struct SM83_pins* pins); // A, C
void SM83_ins_92_SUB_di_di(struct SM83_regs* regs, struct SM83_pins* pins); // A, D
void SM83_ins_93_SUB_di_di(struct SM83_regs* regs, struct SM83_pins* pins); // A, E
void SM83_ins_94_SUB_di_di(struct SM83_regs* regs, struct SM83_pins* pins); // A, H
void SM83_ins_95_SUB_di_di(struct SM83_regs* regs, struct SM83_pins* pins); // A, L
void SM83_ins_96_SUB_di_ind(struct SM83_regs* regs, struct SM83_pins* pins); // A, HL
void SM83_ins_97_SUB_di_di(struct SM83_regs* regs, struct SM83_pins* pins); // A, A
void SM83_ins_98_SBC_di_di(struct SM83_regs* regs, struct SM83_pins* pins); // A, B
void SM83_ins_99_SBC_di_di(struct SM83_regs* regs, struct SM83_pins* pins); // A, C
void SM83_ins_9A_SBC_di_di(struct SM83_regs* regs, struct SM83_pins* pins); // A, D
void SM83_ins_9B_SBC_di_di(struct SM83_regs* regs, struct SM83_pins* pins); // A, E
void SM83_ins_9C_SBC_di_di(struct SM83_regs* regs, struct SM83_pins* pins); // A, H
void SM83_ins_9D_SBC_di_di(struct SM83_regs* regs, struct SM83_pins* pins); // A, L
void SM83_ins_9E_SBC_di_ind(struct SM83_regs* regs, struct SM83_pins* pins); // A, HL
void SM83_ins_9F_SBC_di_di(struct SM83_regs* regs, struct SM83_pins* pins); // A, A
void SM83_ins_A0_AND_di_di(struct SM83_regs* regs, struct SM83_pins* pins); // A, B
void SM83_ins_A1_AND_di_di(struct SM83_regs* regs, struct SM83_pins* pins); // A, C
void SM83_ins_A2_AND_di_di(struct SM83_regs* regs, struct SM83_pins* pins); // A, D
void SM83_ins_A3_AND_di_di(struct SM83_regs* regs, struct SM83_pins* pins); // A, E
void SM83_ins_A4_AND_di_di(struct SM83_regs* regs, struct SM83_pins* pins); // A, H
void SM83_ins_A5_AND_di_di(struct SM83_regs* regs, struct SM83_pins* pins); // A, L
void SM83_ins_A6_AND_di_ind(struct SM83_regs* regs, struct SM83_pins* pins); // A, HL
void SM83_ins_A7_AND_di_di(struct SM83_regs* regs, struct SM83_pins* pins); // A, A
void SM83_ins_A8_XOR_di_di(struct SM83_regs* regs, struct SM83_pins* pins); // A, B
void SM83_ins_A9_XOR_di_di(struct SM83_regs* regs, struct SM83_pins* pins); // A, C
void SM83_ins_AA_XOR_di_di(struct SM83_regs* regs, struct SM83_pins* pins); // A, D
void SM83_ins_AB_XOR_di_di(struct SM83_regs* regs, struct SM83_pins* pins); // A, E
void SM83_ins_AC_XOR_di_di(struct SM83_regs* regs, struct SM83_pins* pins); // A, H
void SM83_ins_AD_XOR_di_di(struct SM83_regs* regs, struct SM83_pins* pins); // A, L
void SM83_ins_AE_XOR_di_ind(struct SM83_regs* regs, struct SM83_pins* pins); // A, HL
void SM83_ins_AF_XOR_di_di(struct SM83_regs* regs, struct SM83_pins* pins); // A, A
void SM83_ins_B0_OR_di_di(struct SM83_regs* regs, struct SM83_pins* pins); // A, B
void SM83_ins_B1_OR_di_di(struct SM83_regs* regs, struct SM83_pins* pins); // A, C
void SM83_ins_B2_OR_di_di(struct SM83_regs* regs, struct SM83_pins* pins); // A, D
void SM83_ins_B3_OR_di_di(struct SM83_regs* regs, struct SM83_pins* pins); // A, E
void SM83_ins_B4_OR_di_di(struct SM83_regs* regs, struct SM83_pins* pins); // A, H
void SM83_ins_B5_OR_di_di(struct SM83_regs* regs, struct SM83_pins* pins); // A, L
void SM83_ins_B6_OR_di_ind(struct SM83_regs* regs, struct SM83_pins* pins); // A, HL
void SM83_ins_B7_OR_di_di(struct SM83_regs* regs, struct SM83_pins* pins); // A, A
void SM83_ins_B8_CP_di_di(struct SM83_regs* regs, struct SM83_pins* pins); // A, B
void SM83_ins_B9_CP_di_di(struct SM83_regs* regs, struct SM83_pins* pins); // A, C
void SM83_ins_BA_CP_di_di(struct SM83_regs* regs, struct SM83_pins* pins); // A, D
void SM83_ins_BB_CP_di_di(struct SM83_regs* regs, struct SM83_pins* pins); // A, E
void SM83_ins_BC_CP_di_di(struct SM83_regs* regs, struct SM83_pins* pins); // A, H
void SM83_ins_BD_CP_di_di(struct SM83_regs* regs, struct SM83_pins* pins); // A, L
void SM83_ins_BE_CP_di_ind(struct SM83_regs* regs, struct SM83_pins* pins); // A, HL
void SM83_ins_BF_CP_di_di(struct SM83_regs* regs, struct SM83_pins* pins); // A, A
void SM83_ins_C0_RET_cond(struct SM83_regs* regs, struct SM83_pins* pins); // regs.F.Z === 0
void SM83_ins_C1_POP_di(struct SM83_regs* regs, struct SM83_pins* pins); // BC
void SM83_ins_C2_JP_cond_addr(struct SM83_regs* regs, struct SM83_pins* pins); // regs.F.Z === 0
void SM83_ins_C3_JP_cond_addr(struct SM83_regs* regs, struct SM83_pins* pins); // 1
void SM83_ins_C4_CALL_cond_addr(struct SM83_regs* regs, struct SM83_pins* pins); // regs.F.Z === 0
void SM83_ins_C5_PUSH_di(struct SM83_regs* regs, struct SM83_pins* pins); // BC
void SM83_ins_C6_ADD_di_da(struct SM83_regs* regs, struct SM83_pins* pins); // A
void SM83_ins_C7_RST_imp(struct SM83_regs* regs, struct SM83_pins* pins);
void SM83_ins_C8_RET_cond(struct SM83_regs* regs, struct SM83_pins* pins); // regs.F.Z === 1
void SM83_ins_C9_RET(struct SM83_regs* regs, struct SM83_pins* pins);
void SM83_ins_CA_JP_cond_addr(struct SM83_regs* regs, struct SM83_pins* pins); // regs.F.Z === 1
void SM83_ins_CC_CALL_cond_addr(struct SM83_regs* regs, struct SM83_pins* pins); // regs.F.Z === 1
void SM83_ins_CD_CALL_cond_addr(struct SM83_regs* regs, struct SM83_pins* pins); // 1
void SM83_ins_CE_ADC_di_da(struct SM83_regs* regs, struct SM83_pins* pins); // A
void SM83_ins_CF_RST_imp(struct SM83_regs* regs, struct SM83_pins* pins); // 8
void SM83_ins_D0_RET_cond(struct SM83_regs* regs, struct SM83_pins* pins); // regs.F.C === 0
void SM83_ins_D1_POP_di(struct SM83_regs* regs, struct SM83_pins* pins); // DE
void SM83_ins_D2_JP_cond_addr(struct SM83_regs* regs, struct SM83_pins* pins); // regs.F.C === 0
void SM83_ins_D3_NONE(struct SM83_regs* regs, struct SM83_pins* pins);
void SM83_ins_D4_CALL_cond_addr(struct SM83_regs* regs, struct SM83_pins* pins); // regs.F.C === 0
void SM83_ins_D5_PUSH_di(struct SM83_regs* regs, struct SM83_pins* pins); // DE
void SM83_ins_D6_SUB_di_da(struct SM83_regs* regs, struct SM83_pins* pins); // A
void SM83_ins_D7_RST_imp(struct SM83_regs* regs, struct SM83_pins* pins); // 16
void SM83_ins_D8_RET_cond(struct SM83_regs* regs, struct SM83_pins* pins); // regs.F.C === 1
void SM83_ins_D9_RETI(struct SM83_regs* regs, struct SM83_pins* pins);
void SM83_ins_DA_JP_cond_addr(struct SM83_regs* regs, struct SM83_pins* pins); // regs.F.C === 1
void SM83_ins_DB_NONE(struct SM83_regs* regs, struct SM83_pins* pins);
void SM83_ins_DC_CALL_cond_addr(struct SM83_regs* regs, struct SM83_pins* pins); // regs.F.C === 1
void SM83_ins_DD_NONE(struct SM83_regs* regs, struct SM83_pins* pins);
void SM83_ins_DE_SBC_di_da(struct SM83_regs* regs, struct SM83_pins* pins); // A
void SM83_ins_DF_RST_imp(struct SM83_regs* regs, struct SM83_pins* pins); // 24
void SM83_ins_E0_LDH_addr_di(struct SM83_regs* regs, struct SM83_pins* pins); // A
void SM83_ins_E1_POP_di(struct SM83_regs* regs, struct SM83_pins* pins); // HL
void SM83_ins_E2_LDH_ind_di(struct SM83_regs* regs, struct SM83_pins* pins); // C, A
void SM83_ins_E3_NONE(struct SM83_regs* regs, struct SM83_pins* pins);
void SM83_ins_E4_NONE(struct SM83_regs* regs, struct SM83_pins* pins);
void SM83_ins_E5_PUSH_di(struct SM83_regs* regs, struct SM83_pins* pins); // HL
void SM83_ins_E6_AND_di_da(struct SM83_regs* regs, struct SM83_pins* pins); // A
void SM83_ins_E7_RST_imp(struct SM83_regs* regs, struct SM83_pins* pins); // 32
void SM83_ins_E8_ADD_di_rel(struct SM83_regs* regs, struct SM83_pins* pins); // SP
void SM83_ins_E9_JP_di(struct SM83_regs* regs, struct SM83_pins* pins); // HL
void SM83_ins_EA_LD_addr_di(struct SM83_regs* regs, struct SM83_pins* pins); // A
void SM83_ins_EB_NONE(struct SM83_regs* regs, struct SM83_pins* pins);
void SM83_ins_EC_NONE(struct SM83_regs* regs, struct SM83_pins* pins);
void SM83_ins_ED_NONE(struct SM83_regs* regs, struct SM83_pins* pins);
void SM83_ins_EE_XOR_di_da(struct SM83_regs* regs, struct SM83_pins* pins); // A
void SM83_ins_EF_RST_imp(struct SM83_regs* regs, struct SM83_pins* pins); // 40
void SM83_ins_F0_LDH_di_addr(struct SM83_regs* regs, struct SM83_pins* pins); // A
void SM83_ins_F1_POP_di_AF(struct SM83_regs* regs, struct SM83_pins* pins); // AF
void SM83_ins_F2_LDH_di_ind(struct SM83_regs* regs, struct SM83_pins* pins); // A, C
void SM83_ins_F3_DI(struct SM83_regs* regs, struct SM83_pins* pins);
void SM83_ins_F4_NONE(struct SM83_regs* regs, struct SM83_pins* pins);
void SM83_ins_F5_PUSH_di(struct SM83_regs* regs, struct SM83_pins* pins); // AF
void SM83_ins_F6_OR_di_da(struct SM83_regs* regs, struct SM83_pins* pins); // A
void SM83_ins_F7_RST_imp(struct SM83_regs* regs, struct SM83_pins* pins); // 48
void SM83_ins_F8_LD_di_di_rel(struct SM83_regs* regs, struct SM83_pins* pins); // HL, SP
void SM83_ins_F9_LD16_di_di(struct SM83_regs* regs, struct SM83_pins* pins); // SP, HL
void SM83_ins_FA_LD_di_addr(struct SM83_regs* regs, struct SM83_pins* pins); // A
void SM83_ins_FB_EI(struct SM83_regs* regs, struct SM83_pins* pins);
void SM83_ins_FC_NONE(struct SM83_regs* regs, struct SM83_pins* pins);
void SM83_ins_FD_NONE(struct SM83_regs* regs, struct SM83_pins* pins);
void SM83_ins_FE_CP_di_da(struct SM83_regs* regs, struct SM83_pins* pins); // A
void SM83_ins_FF_RST_imp(struct SM83_regs* regs, struct SM83_pins* pins); // 56
void SM83_ins_100_S_IRQ(struct SM83_regs* regs, struct SM83_pins* pins);
void SM83_ins_101_RESET(struct SM83_regs* regs, struct SM83_pins* pins);
void SM83_ins_CB00_RLC_di(struct SM83_regs* regs, struct SM83_pins* pins); // B
void SM83_ins_CB01_RLC_di(struct SM83_regs* regs, struct SM83_pins* pins); // C
void SM83_ins_CB02_RLC_di(struct SM83_regs* regs, struct SM83_pins* pins); // D
void SM83_ins_CB03_RLC_di(struct SM83_regs* regs, struct SM83_pins* pins); // E
void SM83_ins_CB04_RLC_di(struct SM83_regs* regs, struct SM83_pins* pins); // H
void SM83_ins_CB05_RLC_di(struct SM83_regs* regs, struct SM83_pins* pins); // L
void SM83_ins_CB06_RLC_ind(struct SM83_regs* regs, struct SM83_pins* pins); // HL
void SM83_ins_CB07_RLC_di(struct SM83_regs* regs, struct SM83_pins* pins); // A
void SM83_ins_CB08_RRC_di(struct SM83_regs* regs, struct SM83_pins* pins); // B
void SM83_ins_CB09_RRC_di(struct SM83_regs* regs, struct SM83_pins* pins); // C
void SM83_ins_CB0A_RRC_di(struct SM83_regs* regs, struct SM83_pins* pins); // D
void SM83_ins_CB0B_RRC_di(struct SM83_regs* regs, struct SM83_pins* pins); // E
void SM83_ins_CB0C_RRC_di(struct SM83_regs* regs, struct SM83_pins* pins); // H
void SM83_ins_CB0D_RRC_di(struct SM83_regs* regs, struct SM83_pins* pins); // L
void SM83_ins_CB0E_RRC_ind(struct SM83_regs* regs, struct SM83_pins* pins); // HL
void SM83_ins_CB0F_RRC_di(struct SM83_regs* regs, struct SM83_pins* pins); // A
void SM83_ins_CB10_RL_di(struct SM83_regs* regs, struct SM83_pins* pins); // B
void SM83_ins_CB11_RL_di(struct SM83_regs* regs, struct SM83_pins* pins); // C
void SM83_ins_CB12_RL_di(struct SM83_regs* regs, struct SM83_pins* pins); // D
void SM83_ins_CB13_RL_di(struct SM83_regs* regs, struct SM83_pins* pins); // E
void SM83_ins_CB14_RL_di(struct SM83_regs* regs, struct SM83_pins* pins); // H
void SM83_ins_CB15_RL_di(struct SM83_regs* regs, struct SM83_pins* pins); // L
void SM83_ins_CB16_RL_ind(struct SM83_regs* regs, struct SM83_pins* pins); // HL
void SM83_ins_CB17_RL_di(struct SM83_regs* regs, struct SM83_pins* pins); // A
void SM83_ins_CB18_RR_di(struct SM83_regs* regs, struct SM83_pins* pins); // B
void SM83_ins_CB19_RR_di(struct SM83_regs* regs, struct SM83_pins* pins); // C
void SM83_ins_CB1A_RR_di(struct SM83_regs* regs, struct SM83_pins* pins); // D
void SM83_ins_CB1B_RR_di(struct SM83_regs* regs, struct SM83_pins* pins); // E
void SM83_ins_CB1C_RR_di(struct SM83_regs* regs, struct SM83_pins* pins); // H
void SM83_ins_CB1D_RR_di(struct SM83_regs* regs, struct SM83_pins* pins); // L
void SM83_ins_CB1E_RR_ind(struct SM83_regs* regs, struct SM83_pins* pins); // HL
void SM83_ins_CB1F_RR_di(struct SM83_regs* regs, struct SM83_pins* pins); // A
void SM83_ins_CB20_SLA_di(struct SM83_regs* regs, struct SM83_pins* pins); // B
void SM83_ins_CB21_SLA_di(struct SM83_regs* regs, struct SM83_pins* pins); // C
void SM83_ins_CB22_SLA_di(struct SM83_regs* regs, struct SM83_pins* pins); // D
void SM83_ins_CB23_SLA_di(struct SM83_regs* regs, struct SM83_pins* pins); // E
void SM83_ins_CB24_SLA_di(struct SM83_regs* regs, struct SM83_pins* pins); // H
void SM83_ins_CB25_SLA_di(struct SM83_regs* regs, struct SM83_pins* pins); // L
void SM83_ins_CB26_SLA_ind(struct SM83_regs* regs, struct SM83_pins* pins); // HL
void SM83_ins_CB27_SLA_di(struct SM83_regs* regs, struct SM83_pins* pins); // A
void SM83_ins_CB28_SRA_di(struct SM83_regs* regs, struct SM83_pins* pins); // B
void SM83_ins_CB29_SRA_di(struct SM83_regs* regs, struct SM83_pins* pins); // C
void SM83_ins_CB2A_SRA_di(struct SM83_regs* regs, struct SM83_pins* pins); // D
void SM83_ins_CB2B_SRA_di(struct SM83_regs* regs, struct SM83_pins* pins); // E
void SM83_ins_CB2C_SRA_di(struct SM83_regs* regs, struct SM83_pins* pins); // H
void SM83_ins_CB2D_SRA_di(struct SM83_regs* regs, struct SM83_pins* pins); // L
void SM83_ins_CB2E_SRA_ind(struct SM83_regs* regs, struct SM83_pins* pins); // HL
void SM83_ins_CB2F_SRA_di(struct SM83_regs* regs, struct SM83_pins* pins); // A
void SM83_ins_CB30_SWAP_di(struct SM83_regs* regs, struct SM83_pins* pins); // B
void SM83_ins_CB31_SWAP_di(struct SM83_regs* regs, struct SM83_pins* pins); // C
void SM83_ins_CB32_SWAP_di(struct SM83_regs* regs, struct SM83_pins* pins); // D
void SM83_ins_CB33_SWAP_di(struct SM83_regs* regs, struct SM83_pins* pins); // E
void SM83_ins_CB34_SWAP_di(struct SM83_regs* regs, struct SM83_pins* pins); // H
void SM83_ins_CB35_SWAP_di(struct SM83_regs* regs, struct SM83_pins* pins); // L
void SM83_ins_CB36_SWAP_ind(struct SM83_regs* regs, struct SM83_pins* pins); // HL
void SM83_ins_CB37_SWAP_di(struct SM83_regs* regs, struct SM83_pins* pins); // A
void SM83_ins_CB38_SRL_di(struct SM83_regs* regs, struct SM83_pins* pins); // B
void SM83_ins_CB39_SRL_di(struct SM83_regs* regs, struct SM83_pins* pins); // C
void SM83_ins_CB3A_SRL_di(struct SM83_regs* regs, struct SM83_pins* pins); // D
void SM83_ins_CB3B_SRL_di(struct SM83_regs* regs, struct SM83_pins* pins); // E
void SM83_ins_CB3C_SRL_di(struct SM83_regs* regs, struct SM83_pins* pins); // H
void SM83_ins_CB3D_SRL_di(struct SM83_regs* regs, struct SM83_pins* pins); // L
void SM83_ins_CB3E_SRL_ind(struct SM83_regs* regs, struct SM83_pins* pins); // HL
void SM83_ins_CB3F_SRL_di(struct SM83_regs* regs, struct SM83_pins* pins); // A
void SM83_ins_CB40_BIT_idx_di(struct SM83_regs* regs, struct SM83_pins* pins); // B
void SM83_ins_CB41_BIT_idx_di(struct SM83_regs* regs, struct SM83_pins* pins); // C
void SM83_ins_CB42_BIT_idx_di(struct SM83_regs* regs, struct SM83_pins* pins); // D
void SM83_ins_CB43_BIT_idx_di(struct SM83_regs* regs, struct SM83_pins* pins); // E
void SM83_ins_CB44_BIT_idx_di(struct SM83_regs* regs, struct SM83_pins* pins); // H
void SM83_ins_CB45_BIT_idx_di(struct SM83_regs* regs, struct SM83_pins* pins); // L
void SM83_ins_CB46_BIT_idx_ind(struct SM83_regs* regs, struct SM83_pins* pins); // HL
void SM83_ins_CB47_BIT_idx_di(struct SM83_regs* regs, struct SM83_pins* pins); // A
void SM83_ins_CB48_BIT_idx_di(struct SM83_regs* regs, struct SM83_pins* pins); // 1, B
void SM83_ins_CB49_BIT_idx_di(struct SM83_regs* regs, struct SM83_pins* pins); // 1, C
void SM83_ins_CB4A_BIT_idx_di(struct SM83_regs* regs, struct SM83_pins* pins); // 1, D
void SM83_ins_CB4B_BIT_idx_di(struct SM83_regs* regs, struct SM83_pins* pins); // 1, E
void SM83_ins_CB4C_BIT_idx_di(struct SM83_regs* regs, struct SM83_pins* pins); // 1, H
void SM83_ins_CB4D_BIT_idx_di(struct SM83_regs* regs, struct SM83_pins* pins); // 1, L
void SM83_ins_CB4E_BIT_idx_ind(struct SM83_regs* regs, struct SM83_pins* pins); // 1, HL
void SM83_ins_CB4F_BIT_idx_di(struct SM83_regs* regs, struct SM83_pins* pins); // 1, A
void SM83_ins_CB50_BIT_idx_di(struct SM83_regs* regs, struct SM83_pins* pins); // 2, B
void SM83_ins_CB51_BIT_idx_di(struct SM83_regs* regs, struct SM83_pins* pins); // 2, C
void SM83_ins_CB52_BIT_idx_di(struct SM83_regs* regs, struct SM83_pins* pins); // 2, D
void SM83_ins_CB53_BIT_idx_di(struct SM83_regs* regs, struct SM83_pins* pins); // 2, E
void SM83_ins_CB54_BIT_idx_di(struct SM83_regs* regs, struct SM83_pins* pins); // 2, H
void SM83_ins_CB55_BIT_idx_di(struct SM83_regs* regs, struct SM83_pins* pins); // 2, L
void SM83_ins_CB56_BIT_idx_ind(struct SM83_regs* regs, struct SM83_pins* pins); // 2, HL
void SM83_ins_CB57_BIT_idx_di(struct SM83_regs* regs, struct SM83_pins* pins); // 2, A
void SM83_ins_CB58_BIT_idx_di(struct SM83_regs* regs, struct SM83_pins* pins); // 3, B
void SM83_ins_CB59_BIT_idx_di(struct SM83_regs* regs, struct SM83_pins* pins); // 3, C
void SM83_ins_CB5A_BIT_idx_di(struct SM83_regs* regs, struct SM83_pins* pins); // 3, D
void SM83_ins_CB5B_BIT_idx_di(struct SM83_regs* regs, struct SM83_pins* pins); // 3, E
void SM83_ins_CB5C_BIT_idx_di(struct SM83_regs* regs, struct SM83_pins* pins); // 3, H
void SM83_ins_CB5D_BIT_idx_di(struct SM83_regs* regs, struct SM83_pins* pins); // 3, L
void SM83_ins_CB5E_BIT_idx_ind(struct SM83_regs* regs, struct SM83_pins* pins); // 3, HL
void SM83_ins_CB5F_BIT_idx_di(struct SM83_regs* regs, struct SM83_pins* pins); // 3, A
void SM83_ins_CB60_BIT_idx_di(struct SM83_regs* regs, struct SM83_pins* pins); // 4, B
void SM83_ins_CB61_BIT_idx_di(struct SM83_regs* regs, struct SM83_pins* pins); // 4, C
void SM83_ins_CB62_BIT_idx_di(struct SM83_regs* regs, struct SM83_pins* pins); // 4, D
void SM83_ins_CB63_BIT_idx_di(struct SM83_regs* regs, struct SM83_pins* pins); // 4, E
void SM83_ins_CB64_BIT_idx_di(struct SM83_regs* regs, struct SM83_pins* pins); // 4, H
void SM83_ins_CB65_BIT_idx_di(struct SM83_regs* regs, struct SM83_pins* pins); // 4, L
void SM83_ins_CB66_BIT_idx_ind(struct SM83_regs* regs, struct SM83_pins* pins); // 4, HL
void SM83_ins_CB67_BIT_idx_di(struct SM83_regs* regs, struct SM83_pins* pins); // 4, A
void SM83_ins_CB68_BIT_idx_di(struct SM83_regs* regs, struct SM83_pins* pins); // 5, B
void SM83_ins_CB69_BIT_idx_di(struct SM83_regs* regs, struct SM83_pins* pins); // 5, C
void SM83_ins_CB6A_BIT_idx_di(struct SM83_regs* regs, struct SM83_pins* pins); // 5, D
void SM83_ins_CB6B_BIT_idx_di(struct SM83_regs* regs, struct SM83_pins* pins); // 5, E
void SM83_ins_CB6C_BIT_idx_di(struct SM83_regs* regs, struct SM83_pins* pins); // 5, H
void SM83_ins_CB6D_BIT_idx_di(struct SM83_regs* regs, struct SM83_pins* pins); // 5, L
void SM83_ins_CB6E_BIT_idx_ind(struct SM83_regs* regs, struct SM83_pins* pins); // 5, HL
void SM83_ins_CB6F_BIT_idx_di(struct SM83_regs* regs, struct SM83_pins* pins); // 5, A
void SM83_ins_CB70_BIT_idx_di(struct SM83_regs* regs, struct SM83_pins* pins); // 6, B
void SM83_ins_CB71_BIT_idx_di(struct SM83_regs* regs, struct SM83_pins* pins); // 6, C
void SM83_ins_CB72_BIT_idx_di(struct SM83_regs* regs, struct SM83_pins* pins); // 6, D
void SM83_ins_CB73_BIT_idx_di(struct SM83_regs* regs, struct SM83_pins* pins); // 6, E
void SM83_ins_CB74_BIT_idx_di(struct SM83_regs* regs, struct SM83_pins* pins); // 6, H
void SM83_ins_CB75_BIT_idx_di(struct SM83_regs* regs, struct SM83_pins* pins); // 6, L
void SM83_ins_CB76_BIT_idx_ind(struct SM83_regs* regs, struct SM83_pins* pins); // 6, HL
void SM83_ins_CB77_BIT_idx_di(struct SM83_regs* regs, struct SM83_pins* pins); // 6, A
void SM83_ins_CB78_BIT_idx_di(struct SM83_regs* regs, struct SM83_pins* pins); // 7, B
void SM83_ins_CB79_BIT_idx_di(struct SM83_regs* regs, struct SM83_pins* pins); // 7, C
void SM83_ins_CB7A_BIT_idx_di(struct SM83_regs* regs, struct SM83_pins* pins); // 7, D
void SM83_ins_CB7B_BIT_idx_di(struct SM83_regs* regs, struct SM83_pins* pins); // 7, E
void SM83_ins_CB7C_BIT_idx_di(struct SM83_regs* regs, struct SM83_pins* pins); // 7, H
void SM83_ins_CB7D_BIT_idx_di(struct SM83_regs* regs, struct SM83_pins* pins); // 7, L
void SM83_ins_CB7E_BIT_idx_ind(struct SM83_regs* regs, struct SM83_pins* pins); // 7, HL
void SM83_ins_CB7F_BIT_idx_di(struct SM83_regs* regs, struct SM83_pins* pins); // 7, A
void SM83_ins_CB80_RES_idx_di(struct SM83_regs* regs, struct SM83_pins* pins); // B
void SM83_ins_CB81_RES_idx_di(struct SM83_regs* regs, struct SM83_pins* pins); // C
void SM83_ins_CB82_RES_idx_di(struct SM83_regs* regs, struct SM83_pins* pins); // D
void SM83_ins_CB83_RES_idx_di(struct SM83_regs* regs, struct SM83_pins* pins); // E
void SM83_ins_CB84_RES_idx_di(struct SM83_regs* regs, struct SM83_pins* pins); // H
void SM83_ins_CB85_RES_idx_di(struct SM83_regs* regs, struct SM83_pins* pins); // L
void SM83_ins_CB86_RES_idx_ind(struct SM83_regs* regs, struct SM83_pins* pins); // HL
void SM83_ins_CB87_RES_idx_di(struct SM83_regs* regs, struct SM83_pins* pins); // A
void SM83_ins_CB88_RES_idx_di(struct SM83_regs* regs, struct SM83_pins* pins); // 1, B
void SM83_ins_CB89_RES_idx_di(struct SM83_regs* regs, struct SM83_pins* pins); // 1, C
void SM83_ins_CB8A_RES_idx_di(struct SM83_regs* regs, struct SM83_pins* pins); // 1, D
void SM83_ins_CB8B_RES_idx_di(struct SM83_regs* regs, struct SM83_pins* pins); // 1, E
void SM83_ins_CB8C_RES_idx_di(struct SM83_regs* regs, struct SM83_pins* pins); // 1, H
void SM83_ins_CB8D_RES_idx_di(struct SM83_regs* regs, struct SM83_pins* pins); // 1, L
void SM83_ins_CB8E_RES_idx_ind(struct SM83_regs* regs, struct SM83_pins* pins); // 1, HL
void SM83_ins_CB8F_RES_idx_di(struct SM83_regs* regs, struct SM83_pins* pins); // 1, A
void SM83_ins_CB90_RES_idx_di(struct SM83_regs* regs, struct SM83_pins* pins); // 2, B
void SM83_ins_CB91_RES_idx_di(struct SM83_regs* regs, struct SM83_pins* pins); // 2, C
void SM83_ins_CB92_RES_idx_di(struct SM83_regs* regs, struct SM83_pins* pins); // 2, D
void SM83_ins_CB93_RES_idx_di(struct SM83_regs* regs, struct SM83_pins* pins); // 2, E
void SM83_ins_CB94_RES_idx_di(struct SM83_regs* regs, struct SM83_pins* pins); // 2, H
void SM83_ins_CB95_RES_idx_di(struct SM83_regs* regs, struct SM83_pins* pins); // 2, L
void SM83_ins_CB96_RES_idx_ind(struct SM83_regs* regs, struct SM83_pins* pins); // 2, HL
void SM83_ins_CB97_RES_idx_di(struct SM83_regs* regs, struct SM83_pins* pins); // 2, A
void SM83_ins_CB98_RES_idx_di(struct SM83_regs* regs, struct SM83_pins* pins); // 3, B
void SM83_ins_CB99_RES_idx_di(struct SM83_regs* regs, struct SM83_pins* pins); // 3, C
void SM83_ins_CB9A_RES_idx_di(struct SM83_regs* regs, struct SM83_pins* pins); // 3, D
void SM83_ins_CB9B_RES_idx_di(struct SM83_regs* regs, struct SM83_pins* pins); // 3, E
void SM83_ins_CB9C_RES_idx_di(struct SM83_regs* regs, struct SM83_pins* pins); // 3, H
void SM83_ins_CB9D_RES_idx_di(struct SM83_regs* regs, struct SM83_pins* pins); // 3, L
void SM83_ins_CB9E_RES_idx_ind(struct SM83_regs* regs, struct SM83_pins* pins); // 3, HL
void SM83_ins_CB9F_RES_idx_di(struct SM83_regs* regs, struct SM83_pins* pins); // 3, A
void SM83_ins_CBA0_RES_idx_di(struct SM83_regs* regs, struct SM83_pins* pins); // 4, B
void SM83_ins_CBA1_RES_idx_di(struct SM83_regs* regs, struct SM83_pins* pins); // 4, C
void SM83_ins_CBA2_RES_idx_di(struct SM83_regs* regs, struct SM83_pins* pins); // 4, D
void SM83_ins_CBA3_RES_idx_di(struct SM83_regs* regs, struct SM83_pins* pins); // 4, E
void SM83_ins_CBA4_RES_idx_di(struct SM83_regs* regs, struct SM83_pins* pins); // 4, H
void SM83_ins_CBA5_RES_idx_di(struct SM83_regs* regs, struct SM83_pins* pins); // 4, L
void SM83_ins_CBA6_RES_idx_ind(struct SM83_regs* regs, struct SM83_pins* pins); // 4, HL
void SM83_ins_CBA7_RES_idx_di(struct SM83_regs* regs, struct SM83_pins* pins); // 4, A
void SM83_ins_CBA8_RES_idx_di(struct SM83_regs* regs, struct SM83_pins* pins); // 5, B
void SM83_ins_CBA9_RES_idx_di(struct SM83_regs* regs, struct SM83_pins* pins); // 5, C
void SM83_ins_CBAA_RES_idx_di(struct SM83_regs* regs, struct SM83_pins* pins); // 5, D
void SM83_ins_CBAB_RES_idx_di(struct SM83_regs* regs, struct SM83_pins* pins); // 5, E
void SM83_ins_CBAC_RES_idx_di(struct SM83_regs* regs, struct SM83_pins* pins); // 5, H
void SM83_ins_CBAD_RES_idx_di(struct SM83_regs* regs, struct SM83_pins* pins); // 5, L
void SM83_ins_CBAE_RES_idx_ind(struct SM83_regs* regs, struct SM83_pins* pins); // 5, HL
void SM83_ins_CBAF_RES_idx_di(struct SM83_regs* regs, struct SM83_pins* pins); // 5, A
void SM83_ins_CBB0_RES_idx_di(struct SM83_regs* regs, struct SM83_pins* pins); // 6, B
void SM83_ins_CBB1_RES_idx_di(struct SM83_regs* regs, struct SM83_pins* pins); // 6, C
void SM83_ins_CBB2_RES_idx_di(struct SM83_regs* regs, struct SM83_pins* pins); // 6, D
void SM83_ins_CBB3_RES_idx_di(struct SM83_regs* regs, struct SM83_pins* pins); // 6, E
void SM83_ins_CBB4_RES_idx_di(struct SM83_regs* regs, struct SM83_pins* pins); // 6, H
void SM83_ins_CBB5_RES_idx_di(struct SM83_regs* regs, struct SM83_pins* pins); // 6, L
void SM83_ins_CBB6_RES_idx_ind(struct SM83_regs* regs, struct SM83_pins* pins); // 6, HL
void SM83_ins_CBB7_RES_idx_di(struct SM83_regs* regs, struct SM83_pins* pins); // 6, A
void SM83_ins_CBB8_RES_idx_di(struct SM83_regs* regs, struct SM83_pins* pins); // 7, B
void SM83_ins_CBB9_RES_idx_di(struct SM83_regs* regs, struct SM83_pins* pins); // 7, C
void SM83_ins_CBBA_RES_idx_di(struct SM83_regs* regs, struct SM83_pins* pins); // 7, D
void SM83_ins_CBBB_RES_idx_di(struct SM83_regs* regs, struct SM83_pins* pins); // 7, E
void SM83_ins_CBBC_RES_idx_di(struct SM83_regs* regs, struct SM83_pins* pins); // 7, H
void SM83_ins_CBBD_RES_idx_di(struct SM83_regs* regs, struct SM83_pins* pins); // 7, L
void SM83_ins_CBBE_RES_idx_ind(struct SM83_regs* regs, struct SM83_pins* pins); // 7, HL
void SM83_ins_CBBF_RES_idx_di(struct SM83_regs* regs, struct SM83_pins* pins); // 7, A
void SM83_ins_CBC0_SET_idx_di(struct SM83_regs* regs, struct SM83_pins* pins); // B
void SM83_ins_CBC1_SET_idx_di(struct SM83_regs* regs, struct SM83_pins* pins); // C
void SM83_ins_CBC2_SET_idx_di(struct SM83_regs* regs, struct SM83_pins* pins); // D
void SM83_ins_CBC3_SET_idx_di(struct SM83_regs* regs, struct SM83_pins* pins); // E
void SM83_ins_CBC4_SET_idx_di(struct SM83_regs* regs, struct SM83_pins* pins); // H
void SM83_ins_CBC5_SET_idx_di(struct SM83_regs* regs, struct SM83_pins* pins); // L
void SM83_ins_CBC6_SET_idx_ind(struct SM83_regs* regs, struct SM83_pins* pins); // HL
void SM83_ins_CBC7_SET_idx_di(struct SM83_regs* regs, struct SM83_pins* pins); // A
void SM83_ins_CBC8_SET_idx_di(struct SM83_regs* regs, struct SM83_pins* pins); // 1, B
void SM83_ins_CBC9_SET_idx_di(struct SM83_regs* regs, struct SM83_pins* pins); // 1, C
void SM83_ins_CBCA_SET_idx_di(struct SM83_regs* regs, struct SM83_pins* pins); // 1, D
void SM83_ins_CBCB_SET_idx_di(struct SM83_regs* regs, struct SM83_pins* pins); // 1, E
void SM83_ins_CBCC_SET_idx_di(struct SM83_regs* regs, struct SM83_pins* pins); // 1, H
void SM83_ins_CBCD_SET_idx_di(struct SM83_regs* regs, struct SM83_pins* pins); // 1, L
void SM83_ins_CBCE_SET_idx_ind(struct SM83_regs* regs, struct SM83_pins* pins); // 1, HL
void SM83_ins_CBCF_SET_idx_di(struct SM83_regs* regs, struct SM83_pins* pins); // 1, A
void SM83_ins_CBD0_SET_idx_di(struct SM83_regs* regs, struct SM83_pins* pins); // 2, B
void SM83_ins_CBD1_SET_idx_di(struct SM83_regs* regs, struct SM83_pins* pins); // 2, C
void SM83_ins_CBD2_SET_idx_di(struct SM83_regs* regs, struct SM83_pins* pins); // 2, D
void SM83_ins_CBD3_SET_idx_di(struct SM83_regs* regs, struct SM83_pins* pins); // 2, E
void SM83_ins_CBD4_SET_idx_di(struct SM83_regs* regs, struct SM83_pins* pins); // 2, H
void SM83_ins_CBD5_SET_idx_di(struct SM83_regs* regs, struct SM83_pins* pins); // 2, L
void SM83_ins_CBD6_SET_idx_ind(struct SM83_regs* regs, struct SM83_pins* pins); // 2, HL
void SM83_ins_CBD7_SET_idx_di(struct SM83_regs* regs, struct SM83_pins* pins); // 2, A
void SM83_ins_CBD8_SET_idx_di(struct SM83_regs* regs, struct SM83_pins* pins); // 3, B
void SM83_ins_CBD9_SET_idx_di(struct SM83_regs* regs, struct SM83_pins* pins); // 3, C
void SM83_ins_CBDA_SET_idx_di(struct SM83_regs* regs, struct SM83_pins* pins); // 3, D
void SM83_ins_CBDB_SET_idx_di(struct SM83_regs* regs, struct SM83_pins* pins); // 3, E
void SM83_ins_CBDC_SET_idx_di(struct SM83_regs* regs, struct SM83_pins* pins); // 3, H
void SM83_ins_CBDD_SET_idx_di(struct SM83_regs* regs, struct SM83_pins* pins); // 3, L
void SM83_ins_CBDE_SET_idx_ind(struct SM83_regs* regs, struct SM83_pins* pins); // 3, HL
void SM83_ins_CBDF_SET_idx_di(struct SM83_regs* regs, struct SM83_pins* pins); // 3, A
void SM83_ins_CBE0_SET_idx_di(struct SM83_regs* regs, struct SM83_pins* pins); // 4, B
void SM83_ins_CBE1_SET_idx_di(struct SM83_regs* regs, struct SM83_pins* pins); // 4, C
void SM83_ins_CBE2_SET_idx_di(struct SM83_regs* regs, struct SM83_pins* pins); // 4, D
void SM83_ins_CBE3_SET_idx_di(struct SM83_regs* regs, struct SM83_pins* pins); // 4, E
void SM83_ins_CBE4_SET_idx_di(struct SM83_regs* regs, struct SM83_pins* pins); // 4, H
void SM83_ins_CBE5_SET_idx_di(struct SM83_regs* regs, struct SM83_pins* pins); // 4, L
void SM83_ins_CBE6_SET_idx_ind(struct SM83_regs* regs, struct SM83_pins* pins); // 4, HL
void SM83_ins_CBE7_SET_idx_di(struct SM83_regs* regs, struct SM83_pins* pins); // 4, A
void SM83_ins_CBE8_SET_idx_di(struct SM83_regs* regs, struct SM83_pins* pins); // 5, B
void SM83_ins_CBE9_SET_idx_di(struct SM83_regs* regs, struct SM83_pins* pins); // 5, C
void SM83_ins_CBEA_SET_idx_di(struct SM83_regs* regs, struct SM83_pins* pins); // 5, D
void SM83_ins_CBEB_SET_idx_di(struct SM83_regs* regs, struct SM83_pins* pins); // 5, E
void SM83_ins_CBEC_SET_idx_di(struct SM83_regs* regs, struct SM83_pins* pins); // 5, H
void SM83_ins_CBED_SET_idx_di(struct SM83_regs* regs, struct SM83_pins* pins); // 5, L
void SM83_ins_CBEE_SET_idx_ind(struct SM83_regs* regs, struct SM83_pins* pins); // 5, HL
void SM83_ins_CBEF_SET_idx_di(struct SM83_regs* regs, struct SM83_pins* pins); // 5, A
void SM83_ins_CBF0_SET_idx_di(struct SM83_regs* regs, struct SM83_pins* pins); // 6, B
void SM83_ins_CBF1_SET_idx_di(struct SM83_regs* regs, struct SM83_pins* pins); // 6, C
void SM83_ins_CBF2_SET_idx_di(struct SM83_regs* regs, struct SM83_pins* pins); // 6, D
void SM83_ins_CBF3_SET_idx_di(struct SM83_regs* regs, struct SM83_pins* pins); // 6, E
void SM83_ins_CBF4_SET_idx_di(struct SM83_regs* regs, struct SM83_pins* pins); // 6, H
void SM83_ins_CBF5_SET_idx_di(struct SM83_regs* regs, struct SM83_pins* pins); // 6, L
void SM83_ins_CBF6_SET_idx_ind(struct SM83_regs* regs, struct SM83_pins* pins); // 6, HL
void SM83_ins_CBF7_SET_idx_di(struct SM83_regs* regs, struct SM83_pins* pins); // 6, A
void SM83_ins_CBF8_SET_idx_di(struct SM83_regs* regs, struct SM83_pins* pins); // 7, B
void SM83_ins_CBF9_SET_idx_di(struct SM83_regs* regs, struct SM83_pins* pins); // 7, C
void SM83_ins_CBFA_SET_idx_di(struct SM83_regs* regs, struct SM83_pins* pins); // 7, D
void SM83_ins_CBFB_SET_idx_di(struct SM83_regs* regs, struct SM83_pins* pins); // 7, E
void SM83_ins_CBFC_SET_idx_di(struct SM83_regs* regs, struct SM83_pins* pins); // 7, H
void SM83_ins_CBFD_SET_idx_di(struct SM83_regs* regs, struct SM83_pins* pins); // 7, L
void SM83_ins_CBFE_SET_idx_ind(struct SM83_regs* regs, struct SM83_pins* pins); // 7, HL
void SM83_ins_CBFF_SET_idx_di(struct SM83_regs* regs, struct SM83_pins* pins); // 7, A

extern SM83_ins_func SM83_decoded_opcodes[0x202];

#endif