#ifndef _JSMOOCH_Z80_OPCODES_H
#define _JSMOOCH_Z80_OPCODES_H

#include "z80.h"
#include "z80_opcodes.h"

// This file mostly generated by sm83_opcodes.js in JSMoo
namespace Z80 {
    extern ins_func decoded_opcodes[1806];
}

#endif
