//
// Created by . on 4/19/25.
//

#include "spc700_disassembler.h"
namespace SPC700 {

static void do_the_thing(jsm_string &out, jsm_debug_read_trace &rt, u32 PC, const char *str)
{
    u32 n = rt.read_trace(rt.ptr, PC + 1) + (rt.read_trace(rt.ptr, PC + 2) << 8);
    out.sprintf("%s %04x:%01x", str, n & 0x1FFF, n >> 13);
}

u32 disassemble(u32 PC, jsm_debug_read_trace &rt, jsm_string &out, u32 p_p)
{
    u32 mdo = p_p << 8;
    u32 opcode = rt.read_trace(rt.ptr, PC);
#define direct_page(n)  rt.read_trace(rt.ptr, (PC+1+(n)+mdo) & 0xFFFF)
#define relative(r, n) ((PC + (r) + (i8)rt.read_trace(rt.ptr, PC + 1 + (n))) & 0xFFFF)
#define r16() (((rt.read_trace(rt.ptr, (PC + 2) & 0xFFFF)) | (rt.read_trace(rt.ptr, (PC + 1) & 0xFFFF))) << 8)
#define r8(n) rt.read_trace(rt.ptr, (PC + 1 + (n)))
    out.quickempty();
#define asm_out(...) out.sprintf(__VA_ARGS__)
#define thing(str) do_the_thing(out, rt, PC, str)

    switch(opcode) {
        case 0x00: asm_out("nop"); return 1;
        case 0x01: asm_out("jst $FFDE"); return 1;
        case 0x02: asm_out("set $%02x:0", direct_page(0)); return 2;
        case 0x03: asm_out("bbs $%02x:0=$%02x", direct_page(0), relative(3, 1)); return 3;
        case 0x04: asm_out("ora $%02x", direct_page(0)); return 2;
        case 0x05: asm_out("ora $", r16()); return 3;
        case 0x06: asm_out("ora (x)"); return 1;
        case 0x07: asm_out("ora ($%02x,x)", direct_page(0)); return 2;
        case 0x08: asm_out("ora #$%02x", r8(0)); return 2;
        case 0x09: asm_out("orr $%02x=$%02x", direct_page(1), direct_page(0)); return 3;
        case 0x0a: thing("orc $"); return 3;
        case 0x0b: asm_out("asl $%02x", direct_page(0)); return 2;
        case 0x0c: asm_out("asl $%04x", r16()); return 3;
        case 0x0d: asm_out("php"); return 1;
        case 0x0e: asm_out("tsb $%04x", r16()); return 3;
        case 0x0f: asm_out("brk"); return 2;
        case 0x10: asm_out("bpl $%04x", relative(2, 0)); return 2;
        case 0x11: asm_out("jst $ffdc"); return 1;
        case 0x12: asm_out("clr $%02x:0", direct_page(0)); return 2;
        case 0x13: asm_out("bbc $%02x:0=$%02x", direct_page(0), relative(3, 1)); return 3;
        case 0x14: asm_out("ora $%02x,x", direct_page(0)); return 2;
        case 0x15: asm_out("ora $%04x,x", r16()); return 3;
        case 0x16: asm_out("ora $%04x,y", r16()); return 3;
        case 0x17: asm_out("ora ($", direct_page(0), "),y"); return 2;
        case 0x18: asm_out("orr $%02x=#$%02x", direct_page(1), r8(0)); return 3;
        case 0x19: asm_out("orr (x)=(y)"); return 1;
        case 0x1a: asm_out("dew $%02x", direct_page(0)); return 2;
        case 0x1b: asm_out("asl $%02x,x", direct_page(0)); return 2;
        case 0x1c: asm_out("asl"); return 1;
        case 0x1d: asm_out("dex"); return 1;
        case 0x1e: asm_out("cpx $%04x", r16()); return 3;
        case 0x1f: asm_out("jmp ($%04x,x)", r16()); return 3;
        case 0x20: asm_out("clp"); return 1;
        case 0x21: asm_out("jst $ffda"); return 1;
        case 0x22: asm_out("set $%02x:1", direct_page(0)); return 2;
        case 0x23: asm_out("bbs $%02x:1=$%04x", direct_page(0), relative(3, 1)); return 3;
        case 0x24: asm_out("and $%02x", direct_page(0)); return 2;
        case 0x25: asm_out("and $%04x", r16()); return 3;
        case 0x26: asm_out("and (x)"); return 1;
        case 0x27: asm_out("and ($%02x,x)", direct_page(0)); return 2;
        case 0x28: asm_out("and #$%02x", r8(0)); return 2;
        case 0x29: asm_out("and $%02x=$%02x", direct_page(1), direct_page(0)); return 3;
        case 0x2a: thing("orc !$"); return 3;
        case 0x2b: asm_out("rol $%02x", direct_page(0)); return 2;
        case 0x2c: asm_out("rol $%04x", r16()); return 3;
        case 0x2d: asm_out("pha"); return 1;
        case 0x2e: asm_out("bne $%02x=$%04x", direct_page(0), relative(3, 1)); return 3;
        case 0x2f: asm_out("bra $%04x", relative(2, 0)); return 2;
        case 0x30: asm_out("bmi $%04x", relative(2, 0)); return 2;
        case 0x31: asm_out("jst $ffd8"); return 1;
        case 0x32: asm_out("clr $%02x:1", direct_page(0)); return 2;
        case 0x33: asm_out("bbc $%02x:1=$%04x", direct_page(0), relative(+3, 1)); return 3;
        case 0x34: asm_out("and $%02x,x", direct_page(0)); return 2;
        case 0x35: asm_out("and $%04x,x", r16()); return 3;
        case 0x36: asm_out("and $%04x,y", r16()); return 3;
        case 0x37: asm_out("and ($%02x),y", direct_page(0)); return 2;
        case 0x38: asm_out("and $%02x=#$%02x", direct_page(1), r8(0)); return 3;
        case 0x39: asm_out("and (x)=(y)"); return 1;
        case 0x3a: asm_out("inw $%02x", direct_page(0)); return 2;
        case 0x3b: asm_out("rol $%02x,x", direct_page(0)); return 2;
        case 0x3c: asm_out("rol"); return 1;
        case 0x3d: asm_out("inx"); return 1;
        case 0x3e: asm_out("cpx $%02x", direct_page(0)); return 2;
        case 0x3f: asm_out("jsr $%04x", r16()); return 3;
        case 0x40: asm_out("sep"); return 1;
        case 0x41: asm_out("jst $ffd6"); return 1;
        case 0x42: asm_out("set $%02x:2", direct_page(0)); return 2;
        case 0x43: asm_out("bbs $%02x:2=$%04x", direct_page(0), relative(+3, 1)); return 3;
        case 0x44: asm_out("eor $%02x", direct_page(0)); return 2;
        case 0x45: asm_out("eor $%04x", r16()); return 3;
        case 0x46: asm_out("eor (x)"); return 1;
        case 0x47: asm_out("eor ($%02x,x)", direct_page(0)); return 2;
        case 0x48: asm_out("eor #$%02x", r8(0)); return 2;
        case 0x49: asm_out("eor $%02x=$%02x", direct_page(1), direct_page(0)); return 3;
        case 0x4a: thing("and $%04x"); return 3;
        case 0x4b: asm_out("lsr $%02x", direct_page(0)); return 2;
        case 0x4c: asm_out("lsr $%04x", r16()); return 3;
        case 0x4d: asm_out("phx"); return 1;
        case 0x4e: asm_out("trb $%04x", r16()); return 3;
        case 0x4f: asm_out("jsp $ff", r8(0)); return 1;
        case 0x50: asm_out("bvc $%02x", relative(+2, 0)); return 3;
        case 0x51: asm_out("jst $ffd4"); return 1;
        case 0x52: asm_out("clr $%02x:2", direct_page(0)); return 2;
        case 0x53: asm_out("bbc $%02x:2=$%04x", direct_page(0), relative(+3, 1)); return 3;
        case 0x54: asm_out("eor $%02x,x", direct_page(0)); return 2;
        case 0x55: asm_out("eor $%04x,x", r16()); return 3;
        case 0x56: asm_out("eor $%04x,y", r16()); return 3;
        case 0x57: asm_out("eor ($%02x),y", direct_page(0)); return 2;
        case 0x58: asm_out("eor $T02x=#$%02x", direct_page(1), r8(0)); return 3;
        case 0x59: asm_out("eor (x)=(y)"); return 1;
        case 0x5a: asm_out("cpw $%04x", r16()); return 3;
        case 0x5b: asm_out("lsr $%02x,x", direct_page(0)); return 2;
        case 0x5c: asm_out("lsr"); return 1;
        case 0x5d: asm_out("tax"); return 1;
        case 0x5e: asm_out("cpy $%04x", r16()); return 3;
        case 0x5f: asm_out("jmp $%04x", r16()); return 3;
        case 0x60: asm_out("clc"); return 1;
        case 0x61: asm_out("jst $ffd2"); return 1;
        case 0x62: asm_out("set $%02x:3", direct_page(0)); return 2;
        case 0x63: asm_out("bbs $%02x:3=$%04x", direct_page(0), relative(+3, 1)); return 3;
        case 0x64: asm_out("cmp $%02x", direct_page(0)); return 2;
        case 0x65: asm_out("cmp $%04x", r16()); return 3;
        case 0x66: asm_out("cmp (x)"); return 1;
        case 0x67: asm_out("cmp ($%02x,x)", direct_page(0)); return 2;
        case 0x68: asm_out("cmp #$%02x", r8(0)); return 2;
        case 0x69: asm_out("cmp $%02x=$%02x", direct_page(1), direct_page(0)); return 3;
        case 0x6a: thing("and !$"); return 3;
        case 0x6b: asm_out("ror $%02x", direct_page(0)); return 2;
        case 0x6c: asm_out("ror $%04x", r16()); return 3;
        case 0x6d: asm_out("phy"); return 1;
        case 0x6e: asm_out("bne $%02x, $%04x", direct_page(0), relative(+3, 1)); return 3;
        case 0x6f: asm_out("rts"); return 1;
        case 0x70: asm_out("bvs $%02x", relative(+2, 0)); return 2;
        case 0x71: asm_out("jst $ffd0"); return 1;
        case 0x72: asm_out("clr $%02x:3", direct_page(0)); return 2;
        case 0x73: asm_out("bbc $%02x:3=$%04x", direct_page(0), relative(+3, 1)); return 3;
        case 0x74: asm_out("cmp $%02x,x", direct_page(0)); return 2;
        case 0x75: asm_out("cmp $%04x,x", r16()); return 3;
        case 0x76: asm_out("cmp $%04x,y", r16()); return 3;
        case 0x77: asm_out("cmp ($%02x),y", direct_page(0)); return 2;
        case 0x78: asm_out("cmp $%02x=#$%02x", direct_page(1), r8(0)); return 3;
        case 0x79: asm_out("cmp (x)=(y)"); return 1;
        case 0x7a: asm_out("adw $%04x", r16()); return 3;
        case 0x7b: asm_out("ror $%02x,x", direct_page(0)); return 2;
        case 0x7c: asm_out("ror"); return 1;
        case 0x7d: asm_out("txa"); return 1;
        case 0x7e: asm_out("cpy $%02x", direct_page(0)); return 2;
        case 0x7f: asm_out("rti"); return 1;
        case 0x80: asm_out("sec"); return 1;
        case 0x81: asm_out("jst $ffce"); return 1;
        case 0x82: asm_out("set $%02x:4", direct_page(0)); return 2;
        case 0x83: asm_out("bbs $%02x:4=%04x", direct_page(0), relative(+3, 1)); return 3;
        case 0x84: asm_out("adc $%02x", direct_page(0)); return 2;
        case 0x85: asm_out("adc $%04x", r16()); return 3;
        case 0x86: asm_out("adc (x)"); return 1;
        case 0x87: asm_out("adc ($%02x,x)", direct_page(0)); return 2;
        case 0x88: asm_out("adc #$%02x", r8(0)); return 2;
        case 0x89: asm_out("adc $%02x=$%02x", direct_page(1), direct_page(0)); return 3;
        case 0x8a: thing("eor $"); return 3;
        case 0x8b: asm_out("dec $%02x", direct_page(0)); return 2;
        case 0x8c: asm_out("dec $%04x", r16()); return 3;
        case 0x8d: asm_out("ldy #$%02x", r8(0)); return 2;
        case 0x8e: asm_out("plp"); return 1;
        case 0x8f: asm_out("str $%02x=#$%02x", direct_page(1), r8(0)); return 3;
        case 0x90: asm_out("bcc $%04x", relative(+2, 0)); return 2;
        case 0x91: asm_out("jst $ffcc"); return 1;
        case 0x92: asm_out("clr $%02x:4", direct_page(0)); return 2;
        case 0x93: asm_out("bbc $%02x:4=$%04x", direct_page(0), relative(+3, 1)); return 3;
        case 0x94: asm_out("adc $%02x,x", direct_page(0)); return 2;
        case 0x95: asm_out("adc $%04x,x", r16()); return 3;
        case 0x96: asm_out("adc $%04x,y", r16()); return 3;
        case 0x97: asm_out("adc ($%04x),y", direct_page(0)); return 2;
        case 0x98: asm_out("adc $%02x=#$%02x", direct_page(1), r8(0)); return 3;
        case 0x99: asm_out("adc (x)=(y)"); return 1;
        case 0x9a: asm_out("sbw $%04x", r16()); return 3;
        case 0x9b: asm_out("dec $%02x,x", direct_page(0)); return 2;
        case 0x9c: asm_out("dec"); return 1;
        case 0x9d: asm_out("tsx"); return 1;
        case 0x9e: asm_out("div"); return 1;
        case 0x9f: asm_out("xcn"); return 1;
        case 0xa0: asm_out("sei"); return 1;
        case 0xa1: asm_out("jst $ffca"); return 1;
        case 0xa2: asm_out("set $%02x:5", direct_page(0)); return 2;
        case 0xa3: asm_out("bbs $%02x:5=$%02x", direct_page(0), relative(+3, 1)); return 3;
        case 0xa4: asm_out("sbc $%02x", direct_page(0)); return 2;
        case 0xa5: asm_out("sbc $%04x", r16()); return 3;
        case 0xa6: asm_out("sbc (x)"); return 1;
        case 0xa7: asm_out("sbc ($%02x,x)", direct_page(0)); return 2;
        case 0xa8: asm_out("sbc #$%02x", r8(0)); return 2;
        case 0xa9: asm_out("sbc $%02x=$%02x", direct_page(1), direct_page(0)); return 3;
        case 0xaa: thing("ldc $"); return 3;
        case 0xab: asm_out("inc $%02x", direct_page(0)); return 2;
        case 0xac: asm_out("inc $%04x", r16()); return 3;
        case 0xad: asm_out("cpy #$%02x", r8(0)); return 2;
        case 0xae: asm_out("pla"); return 1;
        case 0xaf: asm_out("sta (x++)"); return 1;
        case 0xb0: asm_out("bcs $%04x", relative(+2, 0)); return 2;
        case 0xb1: asm_out("jst $ffc8"); return 1;
        case 0xb2: asm_out("clr $%02x:5", direct_page(0)); return 2;
        case 0xb3: asm_out("bbc $%02x:5=$%04x", direct_page(0), relative(+3, 1)); return 3;
        case 0xb4: asm_out("sbc $%02x,x", direct_page(0)); return 2;
        case 0xb5: asm_out("sbc $%04x,x", r16()); return 3;
        case 0xb6: asm_out("sbc $%04x,y", r16()); return 3;
        case 0xb7: asm_out("sbc ($%02x),y", direct_page(0)); return 2;
        case 0xb8: asm_out("sbc $%02x=#$%02x", direct_page(1), r8(0)); return 3;
        case 0xb9: asm_out("sbc (x)=(y)"); return 1;
        case 0xba: asm_out("ldw $%02x", direct_page(0)); return 2;
        case 0xbb: asm_out("inc $%02x,x", direct_page(0)); return 2;
        case 0xbc: asm_out("inc"); return 1;
        case 0xbd: asm_out("txs"); return 1;
        case 0xbe: asm_out("das"); return 1;
        case 0xbf: asm_out("lda (x++)"); return 1;
        case 0xc0: asm_out("cli"); return 1;
        case 0xc1: asm_out("jst $ffc6"); return 1;
        case 0xc2: asm_out("set $%02x:6", direct_page(0)); return 2;
        case 0xc3: asm_out("bbs $%02x:6=$%04x", direct_page(0), relative(+3, 1)); return 3;
        case 0xc4: asm_out("sta $%02x", direct_page(0)); return 2;
        case 0xc5: asm_out("sta $%04x", r16()); return 3;
        case 0xc6: asm_out("sta (x)"); return 1;
        case 0xc7: asm_out("sta ($%02x,x)", direct_page(0)); return 2;
        case 0xc8: asm_out("cpx #$%02x", r8(0)); return 2;
        case 0xc9: asm_out("stx $%04x", r16()); return 3;
        case 0xca: thing("stc $"); return 3;
        case 0xcb: asm_out("sty $%02x", direct_page(0)); return 2;
        case 0xcc: asm_out("sty $%04x", r16()); return 3;
        case 0xcd: asm_out("ldx #$%02x", r8(0)); return 2;
        case 0xce: asm_out("plx"); return 1;
        case 0xcf: asm_out("mul"); return 1;
        case 0xd0: asm_out("bne $%04x", relative(+2, 0)); return 2;
        case 0xd1: asm_out("jst $ffc4"); return 1;
        case 0xd2: asm_out("clr $%02x:6", direct_page(0)); return 2;
        case 0xd3: asm_out("bbc $%02x:6=$%04x", direct_page(0), relative(+3, 1)); return 3;
        case 0xd4: asm_out("sta $%02x,x", direct_page(0)); return 2;
        case 0xd5: asm_out("sta $%04x,x", r16()); return 3;
        case 0xd6: asm_out("sta $%04x,y", r16()); return 3;
        case 0xd7: asm_out("sta ($%02x),y", direct_page(0)); return 2;
        case 0xd8: asm_out("stx $%02x", direct_page(0)); return 2;
        case 0xd9: asm_out("stx $%02x,y", direct_page(0)); return 2;
        case 0xda: asm_out("stw $%02x", direct_page(0)); return 2;
        case 0xdb: asm_out("sty $%02x,x", direct_page(0)); return 2;
        case 0xdc: asm_out("dey"); return 1;
        case 0xdd: asm_out("tya"); return 1;
        case 0xde: asm_out("bne $%02x,x=$%04x", direct_page(0), relative(+3, 1)); return 3;
        case 0xdf: asm_out("daa"); return 1;
        case 0xe0: asm_out("clv"); return 1;
        case 0xe1: asm_out("jst $ffc2"); return 1;
        case 0xe2: asm_out("set $%02x:7", direct_page(0)); return 2;
        case 0xe3: asm_out("bbs $%02x:7=$%04x", direct_page(0), relative(+3, 1)); return 3;
        case 0xe4: asm_out("lda $%02x", direct_page(0)); return 2;
        case 0xe5: asm_out("lda $%04x", r16()); return 3;
        case 0xe6: asm_out("lda (x)"); return 1;
        case 0xe7: asm_out("lda ($%02x,x)", direct_page(0)); return 2;
        case 0xe8: asm_out("lda #$%02x", r8(0)); return 2;
        case 0xe9: asm_out("ldx $%04x", r16()); return 3;
        case 0xea: thing("not $"); return 3;
        case 0xeb: asm_out("ldy $%02x", direct_page(0)); return 2;
        case 0xec: asm_out("ldy $%04x", r16()); return 3;
        case 0xed: asm_out("cmc"); return 1;
        case 0xee: asm_out("ply"); return 1;
        case 0xef: asm_out("wai"); return 1;
        case 0xf0: asm_out("beq $%04x", relative(+2, 0)); return 2;
        case 0xf1: asm_out("jst $ffc0"); return 1;
        case 0xf2: asm_out("clr $%02x:7", direct_page(0)); return 2;
        case 0xf3: asm_out("bbc $%02x:7=$%04x", direct_page(0), relative(+3, 1)); return 3;
        case 0xf4: asm_out("lda $%02x,x", direct_page(0)); return 2;
        case 0xf5: asm_out("lda $%04x,x", r16()); return 3;
        case 0xf6: asm_out("lda $%04x,y", r16()); return 3;
        case 0xf7: asm_out("lda ($%02x),y", direct_page(0)); return 2;
        case 0xf8: asm_out("ldx $%02x", direct_page(0)); return 2;
        case 0xf9: asm_out("ldx $%02x,y", direct_page(0)); return 2;
        case 0xfa: asm_out("str $%02x=$%02x", direct_page(1), direct_page(0)); return 3;
        case 0xfb: asm_out("ldy $%02x,x", direct_page(0)); return 2;
        case 0xfc: asm_out("iny"); return 1;
        case 0xfd: asm_out("tay"); return 1;
        case 0xfe: asm_out("bne y,$%04x", relative(+2, 0)); return 2;
        case 0xff: asm_out("stp"); return 1;
        default:
    }
    return 0;
}
}