//
// Created by . on 2/11/25.
//

#include "gte.h"


enum GTE_reg {
    GTE_VXY0, GTE_VZ0, GTE_VXY1, GTE_VZ1, GTE_VXY2, GTE_VZ2,
    GTE_RGBC, GTE_OTZ, GTE_IR0, GTE_IR1, GTE_IR2, GTE_IR3,
    GTE_SXY, GTE_SXY1, GTE_SXY2, GTE_SXYP,
    GTE_SZ0, GTE_SZ1, GTE_SZ2, GTE_SZ3,
    GTE_RGB0, GTE_RGB1, GTE_RGB2,
    GTE_RES1, GTE_MAC0, GTE_MAC1, GTE_MAC2, GTE_MAC3,
    GTE_IRGB, GTE_ORGB,
    GTE_LZCS, GTE_LZCR,
    GTE_RT11RT12, GTE_RT13RT21,
    GTE_RT22RT23, GTE_RT31RT32,
    GTE_RT33, // returns sign-extended 32-bit
    GTE_TRX, GTE_TRY, GTE_TRZ,
    GTE_L11L12, GTE_L13L21,
    GTE_L22L23, GTE_L31L32,
    GTE_L33,
    GTE_RBK, GTE_GBK, GTE_BBK,
    GTE_LR1LR2, GTE_LR3LG1,
    GTE_LG2LG3, GTE_LB1LB2,
    GTE_LB3, // returns sign-extended 32-bit
    GTE_RFC, GTE_GFC, GTE_BFC,
    GTE_OFX, GTE_OFY,
    GTE_H, GTE_DQA, GTE_DQB,
    GTE_ZSF3, GTE_ZSF4,
    GTE_FLAG
};