# Build all configs for all platforms
# This workflow triggers individual platform builds

name: Build All Platforms

on: 
  workflow_dispatch:

jobs:
  trigger-builds:
    runs-on: ubuntu-latest
    steps:
    - name: Trigger Linux Build
      uses: actions/github-script@v7
      with:
        script: |
          github.rest.actions.createWorkflowDispatch({
            owner: context.repo.owner,
            repo: context.repo.repo,
            workflow_id: 'build-linux.yml',
            ref: context.ref
          })
    
    - name: Trigger Windows Build  
      uses: actions/github-script@v7
      with:
        script: |
          github.rest.actions.createWorkflowDispatch({
            owner: context.repo.owner,
            repo: context.repo.repo,
            workflow_id: 'build-windows.yml',
            ref: context.ref
          })
    
    - name: Trigger macOS Build
      uses: actions/github-script@v7
      with:
        script: |
          github.rest.actions.createWorkflowDispatch({
            owner: context.repo.owner,
            repo: context.repo.repo,
            workflow_id: 'build-macos.yml',
            ref: context.ref
          })
